### ISSUE TITLE
Sol does not stay centered on crossbars when animation rotates the stars in view

### ISSUE THREAD

**Issue by HulaBear** [ljramones/trips#102]
Howdy!  I loaded the stars withing 25 lightyears of Earth and then viewed them while animation made them rotate; zoomed in to Sol and noticed that it does not stay locked onto the intersection of the crossbars for the x-, y-, and z-axis.  Also, the star names should always be readable and facing the viewer; currently those names rotate in the animation and at some points are visible as reversed text.

**Comment by ljramones** [comment]
fixed in 0.5.9
