### ISSUE TITLE
Make stem width controllable in display preferences 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#104]
When the display radius gets large (say 100 LY) the stems are too thin to see, and start exhibiting a moire. 

Add stem width as a parameter in display settings just like you have route and transit width

**Comment by cegannon1** [comment]
Sorry. Thought I'd put in a call for fully definable stems.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ljramones** [comment]
complete
