### ISSUE TITLE
rotation controls are reversed from normal

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#112]
Moving the mouse from right to left should rotate the view clockwise
Moving the mouse from top to bottom should move the front of the grid DOWN and the back UP. 

Both are backwards currently.

**Comment by ljramones** [comment]
done I think

**Comment by BoatrightTBC** [comment]
THANK YOU!!!

This consistently drove me nuts.
________________________________

**Comment by ljramones** [comment]
re-opened. broke it while fixing something else.

**Comment by ljramones** [comment]
back to working
