### ISSUE TITLE
Change distance search to use a shell band

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#115]
change slider to be a lower and upper value in query dialog

we do a query to search for stars from ring 1 to ring 2

**Comment by ljramones** [comment]
complete

**Comment by cegannon1** [comment]
So does this change the basic function for distance searching, or does it create an option? 

I assume it shows up as something like: 

Search for STAR DATA between   X    and    Y light years. (where X could be zero, for a "standard full search".

Or am I misunderstanding?

**Comment by ljramones** [comment]
it looks like this. Basically you would select a lower range and an upper range and it finds all the stars in that shell diameter
![image](https://user-images.githubusercontent.com/226595/99094973-861e6280-25a2-11eb-9d59-ec6194c6c37c.png)

**Comment by ljramones** [comment]
notice that i put major/minor ticks and labels on the range slider
