### ISSUE TITLE
Automated Routing

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#116]
From the Route top level, user picks a find route from A to B

- then a dialog pops up with the 
        -  start star, destination star
        - lower, upper route length bounds, color, line width, and the number of paths to find
- if no exists from start to destination, then an error message comes up that says no path is available
- if a path exits, it will find up to the number requested for paths
- these are displayed to the user who will chose which paths to display as routes
- these routes will then be saved if the user wishes

**Comment by ljramones** [comment]
this is currently 80% done

**Comment by cegannon1** [comment]
Will it indicate the number of shifts?  can one select show least/most first for number legs/shifts? For total ly of route? (Since those are the two most prevalent fiction/gaming concerns.l

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ljramones** [comment]
yes, it tells you how many stops along the way and which star systems. It gives you up tot eh number of different variations form A to B
Choices are ranked from best to worse
It tells you the total length of each
You will see all the choice and pick which you want
e.g. I tested Sol to Delta Pavonis for 3 and 5 paths.  It gave me that many paths choices

**Comment by cegannon1** [comment]
I saw. And it matches what I came up with years ago. ChV obviously gave routes....but not like this!  😁

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ljramones** [comment]
yes, I am using a lot of sophisticated computer science graph search algorithms
I have a couple of things to sort out before its finished , but probably 80% complete
Anyway, hope it matches what you want.
You will have it on Sunday night

**Comment by cegannon1** [comment]
I hope it will run!  Hell, I hope I'll have time to look at it. Very unpredictable here.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ljramones** [comment]
complete
