### ISSUE TITLE
Experiment with GraalsVM as a native JDK to replace our runtime structure to make things easier

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#117]
GraalsVM: https://www.graalvm.org/reference-manual/native-image/

GraalsVM and Spring: https://repo.spring.io/milestone/org/springframework/experimental/spring-graalvm-native-docs/0.8.1/spring-graalvm-native-docs-0.8.1.zip!/reference/index.html#getting-started-native-image

**Comment by ljramones** [comment]
decided to put this off permanently

**Comment by cegannon1** [comment]
Totally cool. Never understood what it meant anyhow. But why the change of heart?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ljramones** [comment]
Permanently means not for a few months (maybe 6). Thats like forever.
