### ISSUE TITLE
Toggle Starts takes an extra click

### ISSUE THREAD

**Issue by TinManOfGames** [ljramones/trips#119]
**Describe the bug**

The first time I select Toggle Stars (with or with out a DataBase loaded) nothing happens 
The Stars are not toggled on or off, the check mark does not show up.
The second time I click on Toggle Stars it functions as expected.

**To Reproduce**

Steps to reproduce the behavior such as:
1. Go to Display
2. Click on Toggle Stars

**Screenshots**

If applicable, add screenshots to help explain your problem. If none, delete this section. You will have to have saved screenshots to your local drive, then just drag and drop them to here in the editor. 

**TRIPS version** 
- [ ] 0.52 
- [ ] 0.53
- [ ] 0.54
- [X] 0.55
 
**Desktop (please complete the following information):** 
 
- [ ] IOS 
- [X] Windows 10

**Comment by ljramones** [comment]
complete
