### ISSUE TITLE
X does not close the Help > About Window ver. is wrong.

### ISSUE THREAD

**Issue by TinManOfGames** [ljramones/trips#121]
**Describe the bug**

When looking at the Help > About window clicking on X does not close the window.
Also the Version number does not appear to be current.

**To Reproduce**

Steps to reproduce the behavior such as:
1. Go to Help
2. Click on About

**Expected behavior vs Actual**

A clear and concise description of what you expected to happen and what you got instead.

**TRIPS version** 
- [ ] 0.52 
- [] 0.53
- [ ] 0.54
- [ X ] 0.55
 
**Desktop (please complete the following information):** 
 
- [ ] IOS 
- [X] Windows 10

**Comment by ljramones** [comment]
complete
