### ISSUE TITLE
UI lack of clear indication of zoom in/zoom out view buttons

### ISSUE THREAD

**Issue by cegannon1** [ljramones/trips#122]
UI issue: Zoom in (+) and Zoom out (-) buttons on screen controls either need to be labeled, or to have a more intuitive image (once again, CHV is a good UI model, if nothing else). HOwever, I think a label is the clearest.  IN the best solution (for users who are do not have English as first language), BOTH would be best. 

Also, location of those screen control elements is crushed up against other controls with which it has nothing in common. Suggest a general UI survey to consider ways of grouping/presenting controls on the UI so that they are grouped by function. (CHV didn't do that quite so well)

Windows 7

**Comment by cegannon1** [comment]
I don't know. Are the generic or proprietary to a creator?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ljramones** [comment]
added icons and hover text to let people know what these buttons do.
