### ISSUE TITLE
CMD still running while TRIPS is

### ISSUE THREAD

**Issue by cegannon1** [ljramones/trips#123]
Users with rudimentary skills could see the current CMD running and, for several reasons, decide/feel it is a spurious drain on their processing resources--or just want to be "tidy"--and so turn it off. 

Since turning it off also terminates TRIPS, this could either baffle users or annoy them. 

Suggest exploration of running TRIPS without the CMD on. Or to make it non-visible. Or to create a warning screen at the entry to the TRIPS indicating that the CMD must be left running. 

It would be great if it were included in documentation at all, but that will only alert a very small percentage of users. 95 % of users will NOT look at documentation, and get annoyed if they feel they have to.

**Comment by ljramones** [comment]
will change the script to use "javaw" instead of "java"

**Comment by ljramones** [comment]
this works, but starup time is still 1 minute.
People will think it is stuck
I will create a splash screen to alert people that it is starting

**Comment by cegannon1** [comment]
Yep. Same on my ancient laptop.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
