### ISSUE TITLE
Screen resolution issue ??? and UI for regular users

### ISSUE THREAD

**Issue by cegannon1** [ljramones/trips#125]
I'm curious about why all the labels are out of focus, just about, regardless of range. I realize that this will be addressed in later iterations from a software perspective. My concern is how these images are displaying on my computer. (see image)

![CEG laptop specs](https://user-images.githubusercontent.com/69170614/94949367-ce7c3800-04ae-11eb-814d-73d83308e21e.png)
![TRIPS 0 5 5 shot](https://user-images.githubusercontent.com/69170614/94949384-d5a34600-04ae-11eb-9d51-b0476d329db2.png)
the stats on my computer appear in the other image. The display setting is currently 1366 x 768. The laptop is about 7 y/o, I believe (label gives no date).

My concern is that I know (personally know) a lot of people whose finances do not allow them to upgrade much at all and are still using comparable machines (I use this one on my treadmill desk because I need a laptop). Which means, if this is about my computer, it's going to be about other computers, also. I really don't want anyone to be left out because they don't have enough money to have a "useful system" for TRIPS.

Is this an issue? It seems to be, moreso than a feature, so I put it here. 

Also, while we're talking about this image, look at the screen label on the bottom margin.
 ,<filename> "is the active context." 
I understand what that means, but a) some users might not, and b) certainly not without thinking. 

Suggestion: 

"You are looking at the stars in <filename>"  Or something similarly phrased in everyday language that tells ANY user which file they're in.

**Comment by ljramones** [comment]
I made changes to reflect this

Also, while we're talking about this image, look at the screen label on the bottom margin.
, "is the active context."
I understand what that means, but a) some users might not, and b) certainly not without thinking.

Suggestion:

"You are looking at the stars in " Or something similarly phrased in everyday language that tells ANY user which file they're in.

**Comment by ljramones** [comment]
with regard to zooming in and labels being out of focus.
I think this is related to the original font size. The labels are drawn as 6 pt font and as you zoom in they are magnified. Its probably do to the magnification effect.
I could do one of three things:
- different font size
- different font
- redraw labels as you zoom in and out (most complicated and higher impact of performance)

I'll experiment

**Comment by cegannon1** [comment]
Here's the thing. As I think is said in a much much earlier issue, you don't want the size of the stars or the letters to really change as you get closer to them.  Wouldn't any fix for that also address this problem as well? If not, the best solution would be one that does a dress and remove this problem.

Best visibility of objects in the display is going to be achieved by making sure that Nothing is growing or shrinking but is remaining the same sides. That makes it easier to keep track of different labels and ensures that a growing label does not occlude one behind it.

That's a really important feature, particularly as you get into displays which are larger than 20 light years of radiusAnd you start moving around in them.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ljramones** [comment]
label remain in focus
