### ISSUE TITLE
Program looks like it has hung when it has not

### ISSUE THREAD

**Issue by cegannon1** [ljramones/trips#128]
Gaia all .csv dataset test

appx 4:20 minutes to load. Should be a warning based on file size/number of entries? Or at least a progress bar? Because the actual data management dialog says, "Not responding" or words to that effect.

No indication that the program is working on it during that time, unless you make sure to be able to watch the CMD sub-window for progress, which accretes in increments of 20 K entyr. Suggest some kind of count-down. Modern users may have no idea just HOW large a dataset this (Gaia) is. need something interactive to make sure they don't give up and turn off.

**Comment by cegannon1** [comment]
![only CMD shows big file load process](https://user-images.githubusercontent.com/69170614/95144591-09000200-0747-11eb-8ade-115c999d60eb.png)

**Comment by ljramones** [comment]
I intend to put a progress screen for long loads.
It's on the list, just haven't got to it yet.
It's a little complicated.
the UI is singlely threaded so I have to invoke some tricky code to get it to show progress

**Comment by cegannon1** [comment]
Got it.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ljramones** [comment]
put in a progress status system. Done
