### ISSUE TITLE
Leaving CMD requires atypical manipulation of its window vis a vis other windows

### ISSUE THREAD

**Issue by cegannon1** [ljramones/trips#129]
When TRIPS has finished loading the dataset, you cannot shift out of the CMD window back to the TRIPS window. That does nothing. You have to REDUCE the CMD window to get it off the screen. I believe this has been a point noted in some other process.

**Comment by ljramones** [comment]
I've added changes in v0.5.6 to reduce the cmd window
will keep up while I check

**Comment by ljramones** [comment]
I believe this is fixed, since after my changes I can't replicate it.
Please reopen if you see it again
