### ISSUE TITLE
Query dialog cannot be repositioned on the screen and the top is cut offf

### ISSUE THREAD

**Issue by cegannon1** [ljramones/trips#131]
Query data dialog cannot be shifted on the desktop. Not indepently of the window of the star view. Also, it does not "follow" a repositioning of the window of the star view.

In the image below, you can still pull the display window all over the place. The Query Dialog will not come with it. Nor can you move it independently.
![Query dialog cannot be moved so it can be used](https://user-images.githubusercontent.com/69170614/95144835-a824f980-0747-11eb-8b20-e67cb151f387.png)

**Comment by ljramones** [comment]
It can be moved

![image](https://user-images.githubusercontent.com/226595/95146063-d48e4500-074a-11eb-894a-69da24e25c7a.png)

and moved here
![image](https://user-images.githubusercontent.com/226595/95146085-ea9c0580-074a-11eb-8fd2-5b1e5c3291ad.png)

I think in your case the top got stuck off screen and that is the part you use to move

I will try ensure that the handle (the top part) can't be stuck

**Comment by cegannon1** [comment]
I mean the window that allows you to identify stars with give. Astrophysical and sapient-added propeties. I think that's the one I showed in the image, no?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cegannon1** [comment]
Ah..okay. yeah. Can it be made grabbable from all edges?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ljramones** [comment]
I'll look into that

**Comment by ljramones** [comment]
I added code to figure out where it will plot and move it so it isn't off screen
