### ISSUE TITLE
Lacks a "Go To/select a Star" command

### ISSUE THREAD

**Issue by cegannon1** [ljramones/trips#132]
Lacks a "Go To/select a Star" command:
 
This is so essential (example follows) that it really should be categorized as a bug, not a feature, I feel. 

There should be an option (a search, better than a menu for this data call) to Go To a star with a given name. Nothing in the menu bar (or its various pull downs),  nor the operation buttons beneath it, suggest that they perform this function. I tried the Query Dialog, but if there is a "search by name" function, I cannot see it because that window cannot be pulled down (so the top of it remains unseeable). 

Example of FREQUENT use: let us say I want to see the route from 55 Tauri (site of Murphy's Lawless) to other systems nearby. Problem: 55 Tauri is appx 151.5 LY from Earth. There should be an obvious command that allows me to choose that star, then the option to center on it. From there, you can run all your desired functions. 

If that option exists, it's presence is not clear...certainly it is NOT being given the focus in the UI that it deserves re: typical use of such programs. If it is in the Query Dialog, it is 
a) not currently visible (possibly cut off with the top of the window; see bug #132, I think, and/or
b) is not phrased/placed in any way that it is an easily detected option. 

Also, Query Dialog is NOT where it should be. "Find Star X" is a top tier navigation commands. It is usually the FIRST in various steps that drill down to more detailed information. It is crucial to avoid playing hide/hunt and seek around starfields. It may be there, but it is not handy nor obvious in its current incarnation.

**Comment by ljramones** [comment]
you will find it here: 
![image](https://user-images.githubusercontent.com/226595/95145808-39956b00-074a-11eb-8608-bee478289697.png)

then start typing the star's name and an autocomplete list will appear
![image](https://user-images.githubusercontent.com/226595/95145923-73ff0800-074a-11eb-8efb-1089ad836421.png)

**Comment by ljramones** [comment]
It will put a highlight on the star so you can see it.
I guess it depends on what else you want to do with the star to make it more visible

I will leave this open for now.

**Comment by cegannon1** [comment]
But what if the star is not "in view"?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ljramones** [comment]
you want to see a star that was not in the query or plotted?

That is pretty much a new query.

In View means the set of all stars that were requested to plot

**Comment by cegannon1** [comment]
That's another case of terminology/clarity. Most people will think "in view" means "presently visible on my screen".

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ljramones** [comment]
I am fine to change the terminology to whatever makes sense

**Comment by cegannon1** [comment]
I'm hesitant to volunteer labels until we have someone with genuine UI and design chops on board. I know my limitations.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ljramones** [comment]
I change the menu to say Select star...

![image](https://user-images.githubusercontent.com/226595/95612734-e06f5500-0a31-11eb-98ec-67ed28c96ba0.png)
