### ISSUE TITLE
Search window stuck in position precluding ability to search for star

### ISSUE THREAD

**Issue by cegannon1** [ljramones/trips#133]
Search subwindow remains stuck to the top of the screen like the Query Dialog does. See image "search subwindow stuck". Repositioning the display window has no effect. When invoked, the search subwindow remains stuck to the top of the screen. 

Note that the subwindow is not useable in this position. A pull-down menu of stars can be accessed, but the space in which to type a star's name does not accept any input. (Probably not enough is registered on screen?). 

Note also that the confusion of labeling this "Stars in View" is further exacerbated by the fact that the pull-down star list offers exactly that: a roster of stars that are LITERALLY in view. So the idea that anyone would presume that "in view" actually means "loaded and available for display and manipulation" is further undermined by this confirmation of the label's most apparent meaning.
![search subwindow stuck](https://user-images.githubusercontent.com/69170614/95405685-78602800-08e6-11eb-8a4d-60bd0eb1aae0.png)
![search subwindow remains stuck](https://user-images.githubusercontent.com/69170614/95405698-7c8c4580-08e6-11eb-911b-8b71d4769ea5.png)

**Comment by ljramones** [comment]
I added code to figure out where it would plot and make sure it would not be off screen
