### ISSUE TITLE
I suggest instead that star names be made visible by hovering over the star shape (tooltip), and the text should then be much larger.

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#158]
as stated

I suggest instead that star names be made visible by hovering over the star shape (tooltip), and the text should then be much larger.

**Comment by ljramones** [comment]
Here's a question.

Currently the stars are visible by default. Do we want a mode where the stars are not visible and become so when we hover over them?

**Comment by cegannon1** [comment]
I see no reason for it. What use do you envision?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ljramones** [comment]
ok, I will close this one as will not do

**Comment by cegannon1** [comment]
Do not understand: "will not do"? As in "this won't work?"

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ljramones** [comment]
you said that you saw no reason to do it.  " see no reason for it"

So I picked the category from the side.  If we need to do something about it then we can open up a clearer issues ticket.

**Comment by cegannon1** [comment]
I think I muat be getting the threads confused.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cegannon1** [comment]
I thought we were still on the blinking selected star topic.

Sorry. Problem is that I can't give this full attention during the day and my nights have becone very difficult. And I will share why.

loom for separate email that I have had to share with about 4 other folks for similar reasons.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cegannon1** [comment]
Sent to eviljinious addy

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
