### ISSUE TITLE
the selected star should be made visible in some other manner than rotation - blinking, external arrow pointing...

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#161]
the selected star should be made visible in some other manner than rotation - blinking, external arrow pointing...

**Comment by ljramones** [comment]
I changed this to a blinking (fade transition) mechanism. It will play this for 60 seconds.
You can either select a star or search for one in view (all visible stars on the screen. The search usied an autocomplete so you star typing the name and it will pop up. Once you select it, it blinks for 60 seconds

**Comment by cegannon1** [comment]
We may want to consider having it continue blinking.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ljramones** [comment]
I'm assuming you want these to eventually stop or you will have a huge number of stars that are blinking.

OR...

you want to toggle the blinking on/off for a set of stars?  If this is what you want, lets setup another issue ticket

**Comment by cegannon1** [comment]
Ah. You said selected STAR so I presumed you were referring to *one* blinking star at a time.

CHV's indicator was only applied to the selected star, the one from which the display radius was measure (which is to say, the star chosen to be the present 0,0,0 reference for the present display).

In the case of a route, the legs of travel point to the relevant  stars pretty effectively.

If there are other reasons to visually mark multiple stars in a single display (search results?) then I agree: flashing should eventually stop.

Maybe an "I need more time" option to "reset the timer"?

Best,

Chuck

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
