### ISSUE TITLE
Change Query dialog

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#169]
On the Query dialog, to the right of the radius put a text display of the number of LY you chose on the slider. DO NOT let people click in it, or they’ll want to type their radius instead of slide for it.

![CleanShot 2021-01-11 at 16 48 09](https://user-images.githubusercontent.com/226595/104242200-cd9f5e80-542c-11eb-93e2-92889e5a3259.png)

**Comment by ljramones** [comment]
changed this to look like this.
the textfields have event listeners that move the slider to what you selected, so for the low range text field, the low range slider value is triggered, and vice versa for high

Likewise the sliders put their values in the textfields

<img width="724" alt="CleanShot 2021-01-11 at 22 05 44@2x" src="https://user-images.githubusercontent.com/226595/104264212-313f8100-5459-11eb-943b-86d1167c78a4.png">

**Comment by cegannon1** [comment]
Again, you are using precise language that I am too ignorant to be *sure* I u.st in a sufficiently detailed and complete fashion. ;)

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
