### ISSUE TITLE
Change Query dialog  for radio from centre

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#170]
The query dialog specifies “Radius from earth.”  If I select a group of stars, possibly using advanced query, that DOES NOT INCLUDE SOL, what happens?    Should that say “Radius from center”?

**Comment by cegannon1** [comment]
Don't knownifbyou took or wlsaw  my commentnon Rick's suggestion (on Slack)

it's imoortant.

posting on Gihub

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by cegannon1** [comment]
I made a comment on this in the slack feed that actually asked for this to be handled in a way that took other factors into account. Can't tell from description if this was followed, or just the comment Rick had here on Github. 

I reprint here: 

Chuck Gannon  10:36 PM
I am liking where all of this is going. My one caveat is, having used and tested a LOT of astrographic programs, I feel that #8 wants an option for either slider or precise entry.
And if I had to choose one over the other, it would be the precise entry.
Here's why:
Searching or viewing a given radius is usually not, in my experience, initiated as a "general curiosity/browsing" exercise. It is usually driven by a need/desire to explore precise data points.
as in:
If star x sends out a radio signal, how far will it have travelled in 67 years?
Same with how far an STL ship could travel/flee in that time.
Also, how many stars with properties x and y but NOT z are within a 45 LY radius of star/object/position x?
And if resource nodes (e.g. green worlds) are how routine travel routes are determined, there is usually an iterative process that considers:
a) how many such systems are within radius z
b) what routes exist between them?
Until you do that kind of analysis, you cant't see where the hubs are, particularly when you stat cranking in the jump/shift/fuel ranges of the ships of that polity.
BTW, I have had frequent recourse to ALL of these analyses using CHV (often very cumbersome) in creating/discovering the underlying data drivers of the Caineverse's differing polities. And this is really not just author judgment but simply being able to see the way the stars are arranged. The oft-referenced Green Mains of the CTR arise directly from this kind of multivariate analysis.
in all cases PRECISE distance values are key. So having to fiddle with a slider to get an exact value? Maybe not worth the "intuitive" slider.

LJ Ramones  10:47 PM
well, between the two of you, pick a modality of selection. Writing code does take time and I would rather do it once than write code, rewrite, then rewrite again.

rboatright  12:23 AM
Fair enough.  Here's my take.  I like the slider, it's easy to mess with if you're playing around.  I get Chuck's point about precision.  Therefore....   as much as I know this is a pain, can you do both?
12:24
Min Dist [........]  SLIDE------x------x------x----ER  Max Dist [.......]

LJ Ramones  8:54 AM
Sure
8:56
I’ll tie the range slider event and text events together so when you enter values the slider moves and when you move the slider the values appear






rboatright  10:13 AM
that would be perfect

Chuck Gannon  10:22 AM
See. And I woukdn't even know to suggest a thing.

**Comment by ljramones** [comment]
Chuck, you comments belong on the other one.  This is just relabelling the distance form centre
