### ISSUE TITLE
Change Trips preferences pane in side panel

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#18]
from Rick:
Take everything above and apply them to "Trips Preferences." What's more annoying is there's this lovely "Change" button, but it doesn't DO anything, and you can't edit the values above, nor does it open a preferences editing window.  What's it supposed to do ? 

I'll remove that and make a fully fledged dialog for it

**Comment by EvilJinious1** [comment]
ok, I broke this out and put it in its own dialog.  I ran out of time to make all the changes but you can see it in change application preferences in one of the menus

**Comment by EvilJinious1** [comment]
ok, I fixed it in v0.4

**Comment by ljramones** [comment]
need to connect preferences into the application

**Comment by ljramones** [comment]
ok, all of this was broken up into two functions, one to see the properties and another to change them.
