### ISSUE TITLE
Discover why some stars are not being plotted correctly

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#199]
https://docs.google.com/document/d/1C0kGSl3i2SYXbhcPwmdo0_qUW5ybbI8mlJhbN1lMU20/edit?ts=601640ed#

at several points in this document, it mentions that some extensions or routes. transits are linked to "invisible" stars.

A question is why are these stars being plotted properly on screen.

This is an open ended issue and may take time

**Comment by ljramones** [comment]
refer to #214 as this is the same issue but the details as to why are there

**Comment by cegannon1** [comment]
I have no idea who sees these emails.

However, if I am understanding this issue correctly, the route line indicator runs off the display.

One of the things that happened in CHV was that when you plot a route between starsOne of the things that happened in CHV was that when you plot a route between stars, The display  Gives you a look at that entire route although it only displays the stars in that route.

Then when you come out of viewing the route it returns you to the Original display. I am not suggesting this as a standard but it might be a desirable feature. To be able to click back-and-forth between the standard display with the route imposed upon it, versus a route only display which would show the entire route and only the stars that full upon that route.

Please confirm that this has been received.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by ljramones** [comment]
I get instant notification when anyone comments and read them the moment I have a chance. I prefer this narrow focus because it keeps all the conversation on a specific topic focused and its easy to find.

>>> The problem that Rick pointed out was actually two different items.

1) One was that the backing store got out of data as to what stars were on the screen.

2) The second problem was that the labels for routes and transits were being drawn when they should be suppressed when the lines they were describing were off screen.

If the labels were part of the object being displayed then all of this would be taken care of. But unfortunately, because having the entire structure being able to rotate and simultaneously keep the label flat (they counter rotate) requires that I have a separate mechanism to handle labels.

But applying a clipping algorithm is straightforward and doesn't require me to rewrite the graphics system.

The route and transit label clipping is discussed here: https://github.com/ljramones/trips/issues/215
The missing stars is discussed here: https://github.com/ljramones/trips/issues/214

These two issues are still open and I am working on this when I have the opportunity
