### ISSUE TITLE
ability to DRAG  plot view in addition to rotate. 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#20]
If you zoom in the plot view, sometimes, you want to view a cluster of stars near an edge, not just the center. 

Ideally, ctrl-drag or shift-drag, or rightclick-drag should shift the plot view as opposed to rotating it.

**Comment by EvilJinious1** [comment]
ok, I'll have to look into doing that

**Comment by ljramones** [comment]
crtl drag for now
mouse wheel zooms in and out
