### ISSUE TITLE
fix status panel

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#201]
still badly sized on Windows version but works fine on Mac version

Need to figure this one out

**Comment by cegannon1** [comment]
I would appreciate this a lot. Hard to get a sense of  Some things with the display running in the equivalent of a window Box

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ljramones** [comment]
It looks like this has been fixed by changing the size of the applied panel
