### ISSUE TITLE
In route finder typeahead stops on a space

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#210]
When entering stars for selecting routes, the system stops reading if you type a space.  For example, using the above dataset, try to enter "HD 156384".When you press space after HD, the selection box goes away and the combo box is blank. Obviously, this is a problem if you have lots of stars from the same catalog.

**Comment by ljramones** [comment]
space is consumed deep within the combo box and so I can't add it as a filter for the name.

I did add digit and * so you could use these other values to search.

**Comment by cegannon1** [comment]
Sorry, I *think* I understand the limitations.  It sounds like a user info box may want to be nationally assigned to this (sounds like user entered *, rather than a typeahead),.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ljramones** [comment]
the type ahead is used for the on screen display of stars of at most you are looking at about 200. typing a few characters weans that down to a handful so not having a space is not detrimental.

**Comment by ljramones** [comment]
however, I didn't put a typeahead for the entire 300k dataset. I would have to use a much more sophisticated technology for that. 
The typeahead works on what's in memory. As such, you have real limitations on how many stars you can have in memory and keep the requirements for running TRIPS accessible to most people. More memory -> more powerful computer.

**Comment by cegannon1** [comment]
Got it.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
