### ISSUE TITLE
Star label expands far too much as point of view gets closer a star

### ISSUE THREAD

**Issue by cegannon1** [ljramones/trips#23]
Greater proximity to star when in view mode expands its label. Not a desirable feature. 
I think CHV had this right where there was little if any change in label size, and only moderate change (if any) in the size of the star icon. 
I cannot look at CHV on the machine from which I am responding currently, but I think only slight change in label should be applied. At close approach (see attached screenshot), the label has expanded to become an obstruction to vision and orientation to other stars. 
![Star label focus degradation when proximal](https://user-images.githubusercontent.com/69170614/90988508-3e6ada80-e561-11ea-848a-b1d555fb322e.png)

**Comment by EvilJinious1** [comment]
It's a 3D scene so the size of the label is realistic to what a 3D scene would be like is you move in.
This may be tricky to do as I would have to dynamic resize the labels as the scene is changed

**Comment by ljramones** [comment]
label now remains the same size at any range
