### ISSUE TITLE
When side pane is displayed, star field is not centered in the star field window. 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#240]
When you open the side pane, the star field is displayed in the star field window as though the center of the field is offset by the width of the side pane. 

Apparently, the star field is being plotted in a "virtual window" that still has the same width as before instead of being reduced in width by the width of the side pane.  

This persists even if you maximize or re-size the overall TRIPS window.  

As a result, some of the star field is off screen to the left.

**Comment by ljramones** [comment]
when the side panel is opened, I do a translate sideways. I translate back when the side panel is closed.

The translate back seems to require a different size that the initial one. Initially I used 300 left then 300 right, but the 300 right (moving back) was 6 times too much. So I switched it to 300 left, then 50 right to get it roughly in the same place.

The star field is plotted in a canvas that clips the ends of what can be displayed and what shouldn't

I'll have to experiment as to why.

**Comment by ljramones** [comment]
I was re-reading this and I think I initially misunderstood the issue of what you are reporting.
So do you want to me to make the star field smaller when the side panel opens and then put it back to same size when I close the side panel?

**Comment by BoatrightTBC** [comment]
Hmmm.  interesting.  I think I hadn't thought about it, but...

Yes, that's a much better way of putting it.

________________________________

**Comment by ljramones** [comment]
ok, I'll sort this out, now that I get what you want

**Comment by ljramones** [comment]
alright, I made a change so that when you open the side panel, it zooms the plot out and then in when the side panel is closed.
So for the default settings it seems fine.
There are still some issues on resize which I might have to adjust for
