### ISSUE TITLE
Select Stars - 'none' doesn't work.

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#248]
**Under polities (I didn't check anything else) "none" doesn't work*

Use the 70 LY xlsx data set. 

I marked 3 stars as "Terran" in edit data.  Which ones are not important. 

I marked 3 stars as "Dornani" in edit data. Ditto. 

In "Select Stars" I click yes for polity, and chose Terran, or Dornani and plot and those 3 stars for each plot. 

I click on both Terran and Dornani and I get six stars.  So far all good. 

With 'yes' unchecked on polity, I get 211 stars within 28.11 LY in the 70LY xls dataset.  So, if I check Terran and "none" I am expecting 208 stars, everything except the Dornani.  

Instead, I get three stars.  The technical term for this is "wrong." :-)

**Comment by cegannon1** [comment]
Are the 3 stars you got in the error the three Terran stars?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Rick Boatright ***@***.***>
Sent: Friday, March 12, 2021 7:31:44 AM
To: ljramones/trips ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ljramones/trips] Select Stars - 'none' doesn't work. (#248)


*Under polities (I didn't check anything else) "none" doesn't work

Use the 70 LY xlsx data set.

I marked 3 stars as "Terran" in edit data. Which ones are not important.

I marked 3 stars as "Dornani" in edit data. Ditto.

In "Select Stars" I click yes for polity, and chose Terran, or Dornani and plot and those 3 stars for each plot.

I click on both Terran and Dornani and I get six stars. So far all good.

With 'yes' unchecked on polity, I get 211 stars within 28.11 LY in the 70LY xls dataset. So, if I check Terran and "none" I am expecting 208 stars, everything except the Dornani.

Instead, I get three stars. The technical term for this is "wrong." :-)

**Comment by BoatrightTBC** [comment]
Yep.  THAT part worked perfectly.

I labeled 3 random stars as Terran, 3 random stars as Dornani.

Ask for terran, get the 3 terran stars.  Ask for terran and none, get the 3 terran stars.

Ditto Dornani.  3 D's with and without "none.

Then,  ask for terran AND dornani AND none, get six stars.

________________________________

**Comment by ljramones** [comment]
I'll get to this one later tonight.
I expect to fix all these by Sunday.

I'll also need to have those keyboard mappings to finalize those two keyboard issues

**Comment by ljramones** [comment]
ok, just to clarify, selecting Terran and none means that you want anything marked Terran and anything not marked with a polity

**Comment by cegannon1** [comment]
Correct

**Comment by ljramones** [comment]
ok, fixed this.

Found a different problem with initialization of star data. I will write a ticket for this to make the initial data consistent
