### ISSUE TITLE
Provide a way to force a star's name to show. 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#259]
I'm not suggesting that we add a "Show star name" checkbox, 'cause I'm tired of changing the database... although I guess that could be an internal only thing. 

Does the algorythm give a star "lots of points" for having a polity?  If so, then adding anything to polity would be the same thing as forcing star name to show. 

Anyway, we need some way to force name showing.  I guess we could add a checkbox.  I'm not going to tell you how to do it.

**Comment by ljramones** [comment]
do you want it to be persistent beyond each run?

If so then it needs to be in the DB. I can make that an internal structure that isn't part of the load.

**Comment by BoatrightTBC** [comment]
Yes.  It needs to be persisted. If that means I'm going to have to have the install trash the data folder again, make sure I know.    If we're going to do that, we probably want to put it in the import too...

**Comment by ljramones** [comment]
ok, I will run the force name like this.
If you set the polity or any of the fictional attributes like world type, etc it toggles the force name to be shown.

Any other attributes to force on?

**Comment by cegannon1** [comment]
Maybe I am not understanding correctly. But with this be for all worlds in view? In other words, if I'm looking at a 30 light year radius area, and we put in all the defined world in the term Republic and the other alien polities, it's going to be unreadable litter. Or maybe I'm not understanding this for

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ljramones** [comment]
Ok, but you guys need to define the criteria for when a label is to be always shown.

I'll put in support for it, but leave out the automated criteria for setting it.

It will exist but not function until you and Rick defined exactly how you want it to happen.

**Comment by ljramones** [comment]
ok, changes made.

Please define the criteria for enabling it.

**Comment by cegannon1** [comment]
I wish I could, but I run into the same problem as always. I lack:

1) knowing what can be done by the code
2) knowing how my suggestions might impact other program architectures
3) how much labor it will take

My common sense proposition is to start from what we know we DON'T want it to do. 

Answer: whatever we set, it cannot be simple on/off. Which makes me think that maybe it should be included in the display algorithm, instead. 

But I have no idea what value I would set for it, since I have long since lost sight of the algorithms (and they have changed significantly). 

Another concept: I am not sure we want to show the name. Maybe we just want to change the way the star is displayed. And that can be toggled on and off. 

Note that the aforegoing would be different than a search: it would be a non-polity specific "at-a-glance" of polity worlds. And it could be made more sophisticated (as in; is their a population or other living presence in the system vs. simply claimed), but I would leave that for later. 

I think there may be a way to blend these. 
Show polities
Show polities with system names

either one modified by "if system is populated"

what do you think?

**Comment by cegannon1** [comment]
UI suggests these should be ganged in a menu pull down to avoid clutter. 
"Mark Polities" ??

**Comment by ljramones** [comment]
I made the changes in the database for force label thusly:

- if a star is marked as force label, then that star is always labelled
- the forced labels are always counted in the "number of labels to show" so they don't create the effect of # of forced labels + # of labels to show.  It will subtract from the numbers of labels.

What isn't there is a means to force a label or automated criteria for ensuring that a label becomes forced.

The simplest thing is to have a drop down that toggles it to on or off.

Once you and Rick tell me the criteria, I can finish the implementation.

As for showing polities, I use a color Halo around the stars wit a unique halo color for each. You can change these as you wish. If you want a different default color, let me know.

![CleanShot 2021-03-21 at 17 46 36](https://user-images.githubusercontent.com/226595/111921890-6970ca80-8a6d-11eb-802a-0fa6287f50b1.png)

I tried putting a ring around the star but it looks awful. If you want another mechanism then please let me know what it is.

**Comment by cegannon1** [comment]
did u c my suggestions?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by cegannon1** [comment]
I have reservations about what Force Label will do in terms of  Comparative orientation. By which I mean, as you start to use the displays come to you start to get a handle on certain stars that almost always show up, kind of the way that certain stars were always used to navigate by on our seas.

I think force all is likely to bump all of those off the grid, because most views in any sort of polity are going to probably eat up a 3rd to a 1/2 or all ofThe 30 named slots.

How hard is this....

No more than 10 Polity stars may  Have there names  Appear on any display.  If There are multiple polities, at least one of each polity is displayed. the rest are displayed based on their normal display ranking.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ljramones** [comment]
For this, "No more than 10 Polity stars may  Have there names  Appear on any display.  If There are multiple polities, at least one of each polity is displayed. the rest are displayed based on their normal display ranking."

This is easy. Do you want the 10 to be user selectable?

But still, there is a question on how force label is triggered. Do we want it to be a manual action? Do we want an automated capability for forcing labels.

If we can answer this, I can finish it

**Comment by cegannon1** [comment]
Hi Larry:

What I’d like to get is Rick’s take on the results to appearance and usability, in that the two of us banged around with what CHV did and did not do, and I don’t trust my own mind’s eye, solo.

My instinct is to tuck away any checklist (which polities to flag) in a sub-sub menu. It’s the sort of thing that can get low-power users confused with too many choices.

I think force label has got to be a user manual function. I mean, we can TRY it with an automated setting, but I am juggling too many balls to be sure I’d have the decision path straight in my head. Just between now and afternoon, I thought it through, made my suggestions….and the logic path is gone.

I’m editing three novellas (other folks in Murphy’s Lawless part of the Caineverse), finishing the fantasy novel, and wrangling website issues and etc. I’m also outlining/writing forward on the second fantasy novel and collecting snippets/writing forward to the braided novel I’ll be creating out of the three novellas.

It’s hard to keep THAT many projects straight (and that the 4 month horizon; there are at least twice as many over the next 8 months).

So I’m asking Rick to chime in, double check my thinking.

Best and thanks again,

chuck

**Comment by BoatrightTBC** [comment]
There are two different things going on here.   I'm going to distinguish them: 

# Scenario One

Author Bob is writing an epic about the humans interactions with the worm people who's home planet is Ross 154.  Bob wants Ross 154 to always show its name whenever it is in view.  It's important beyond all other issues, in fact, he may have edited the star's entry in the database and changed the name to WormHome.  

This scenario simply requires we add a checkbox to the star database...  "Always show name" and it it's checked, then we do.  There is another way to handle it. We have a base "display score" stored with each star based on a long list of criteria.  We could make that value editable, and Bob could give WormHome a base display value of 9999  --  but from a human factors point of view, the checkbox is better. 

# Scenario Two

## Problem One: Names clustered toward center

We have an algorithm that decides if any particular star has its name shown in any particular view. When I sent that algorithm to Larry, i never expected that it was the final one.  As it turns out, it sucks. It is MASSIVLY too central weighted.  

I'm going to try propose something more along the lines of what we actually need. 

If you take a display sphere of X light years, and divide it into four nesting spherical shells, each larger than the other, they each have a volume larger than the one inside of it.  

If you have a sphere with a radius of four light years, the outer one lightyear thick shell has a volume 

V = (4/3) * Pi * (4^3 - 3^3) = 155 Cubic Light years.
the next three shells in have volumes of 80, 29, and 4 cubic light years (rounding to integers) 

So, if we wanted to spread the names out over VOLUME of the spherical shells, over the 267 cubic light years in the sphere we need to chop our distance calculation up into **four bands**. 

So, if we have some number of names we've told the system to display -- let's say 30 names...  then the names to display for each shell are: 

Total Number to display * (volume of shell / Volume of display)  

For each shell, we can pre-calculate the (volume of that shell / volume of display)

Inner:    0.0156
Level 2:  0.109
Level 3:  0.312
Outer:    0.687

So, if we want to display 30 names, the count of names in each shell is 1,4,10,20

Yes, I know that's more than 30, but it's a rational way to allocate them. 

So We take the Base Display Score for the stars with distance from center <= display/4 and only the top display score gets its name shown. 

For stars with distance from center > display/4 and <= display/2 the top four get name shown. 

For stars with distance > display/2 and <= display * 3/4 the top 10 get names and 

in the outer shell, distance > display * 3/4 the top 21 get names.  

Basically, do what you're already doing, and them choose what to name based on distance in four passes...  i've come up with nothing hetter. 

## Problem Two - We forgot a factor in the Display base score

We need to add two more lines to the "multiplier", I.E. the first part of the display score that doesn't change with time or display diameter or whatever. 

Score   Explanation
3    | Is there something in the Common Name   field?
3    | Does the star have a Flamsteed catalog ID?
3    | Does the star have a Bayer catalog ID?
1    | Is the star in the BD catalog?
1    | Is the star in the Gliese catalog?
2    | Is the star in Hipparchos?
1    | Is the star in Henry Draper?
3    | Does the star have an entry in Polity?
3    | Does the star have an entry in any of the other   "fictional" fields?  (Counts   once no matter how many)

The bottom two criteria are new.  

I've spent the evening running simulations, and this is the best I can come up with.  I'm sorry it's so complex, but now I understand why Jo did it the other way, simply tagging stars to always display.

**Comment by cegannon1** [comment]
I posted a very-very-very long statement about what to do with star names
in the issue.  Did I mention long?  It involves as FEW changes to the
program as possible at this point.

I do NOT want to add anything like "valuing" one polity over another at
this point.  Way too deep in the weeds.  We don't have a consistent UI
design for anything like that.  No no nonononono

See my nice LONG writeup about modifying how we choose the names to
display.

**Comment by BoatrightTBC** [comment]
So, final outcome after discussing it with Chuck at this point. 

#### Do both of the things described in my post above -- a checkbox or = to force A stars name to show and the modifications to the "choosing names" calculation. 

At this point, in **THIS** issue we choose not to address polities, because we have a change/enhancement we want to talk about re displaying polities in a different issue with different importance.  It's not just about names.  You can take the comment above from me ask specs.

**Comment by ljramones** [comment]
I've added the 2 additional heuristics for polity and other fictional info.
I've added the check to force a label to be shown.
This is persisted int he DB.

I haven't added this parameter tot he import logic as that requires me to change the importer (all 4 of them and Rick would have to recreate his datasets. If you want this then let me know along with the caveats that I have pointed out.

It's also done. I just have to test it.

**Comment by BoatrightTBC** [comment]
Works, thanks Larry

**Comment by cegannon1** [comment]
I know all the words,, but I don't  know what it means in terms of

*program features/capabilities
*consequences of the team's time, labor etc

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ljramones** [comment]
Work is completed as specified in the issue ticket.
I just specified the constraints on its use. The only real constraint is that you can’t specify it on initial import of a new file.

**Comment by ljramones** [comment]
done
