### ISSUE TITLE
Desired feature: ability to change format of grid and extension lines 

### ISSUE THREAD

**Issue by cegannon1** [ljramones/trips#26]
It is desirable to be able to change format of grid and extension lines. Specifically, to large-dashed or small-dashed lines. CHV made effective us of this as a further method of cueing the observer to being able to track whether they are looking at a grid line (x, y axes) or vertical (z axis "extension"). 

I went back and checked CHV and discovered that in the default display mode, there was not difference in the color of the grid and extension lines. Their only difference was that the grid lines were dashed. The extension was solid. This worked very well, because the constant presence of the grid across the screen makes it easy to orient on. The extensions, not so--but the solid line was an excellent cue that let the eye see the "z axis" in juxtaposition with extreme ease. 

I attach two short videos of the CHV starfield in rotation. It shows no change in star icon size or label. I think a *small* change in either would be worth trying out. But orientation of the observer will be lost if the objects in the field of view change to dramatically. Use of TRIPS will be very much like CHV in that it will have far more utility as a "big picture" viewer. It is not for viewing on star or a few, but a dozen or more in a volume of space. 

Whatever CHV's many programming oddities, inelegances, and imperfections might be, the one thing it got pretty right was a fine balance when it came to viewer properties. It is simple, with very few different icons or labels, and most of those are self-explanatory/intuitive. The real focus was on creating the "faux-3d" for purposes of rotation to get a sense of relative position of all objects. As a result, the objects did not change size, nor did their labels. I suspect that if it is not too intensive on processing power, some small amount of change would be helpful...but I don't think we can know until/unless we see it. Big change is an impediment to clarity, however. 

Even the font choice for the labels (segue narrow, I think) follows with that objective: it strikes a careful balance between readability with low profile (in re: to the screen space any given character requires). 

I am not enamored of CHV, but I think its visuals are a good starting point. Rather than reinvent the wheel, I would like to suggest that we try to stick close to them and THEN alter as seems best in terms of clarity, as balanced against the costs against processing and possible lag on older machines. 

Okay, I have to zip the videos. Sorry.
[Hand held zoom out of complex CHV field.zip](https://github.com/EvilJinious1/trips/files/5115056/Hand.held.zoom.out.of.complex.CHV.field.zip)
[CHV large field in rotation.zip](https://github.com/EvilJinious1/trips/files/5115059/CHV.large.field.in.rotation.zip)

**Comment by EvilJinious1** [comment]
working on that now

**Comment by ljramones** [comment]
complete
