### ISSUE TITLE
Sorting problem when editing stars. 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#260]
You've loaded some dataset. You want to edit some stars.  The stars in the dataset come up in alphabetical order, which is good, and as you page down through them, they are in alphabetical order. 

But then, for some reason, you want to edit some stars that you can find by distance, or by spectral class or by something. So, then you notice that clicking on the column headings causes it to sort.  That's cool. 

But then, the giant disappointment.  You click spectral class, and it appears to sort by spectral class, and then you hit "next page" or "end"... and if you hit end, you're not in the Y's and Z's... and if you hit next, suddenly you're seeing a spectral class that should be ABOVE the one I started on because the sort, only sorts THE PAGE YOU ARE ON.  -- Which sucks.  

So, either we need the sort to sort the data on however many pages there are, or we need to disable the sorts. 

Right now, as it is, the sorts are an anti-feature.  They actually make the program worse.

**Comment by ljramones** [comment]
It does sort the backing list according to the criteria (ascending or descending.

What I think happens is that the it tries to preserve the current page and that ends up messing things up.

What I believe I should do is put the list back at the first page after the sort happens.

@BoatrightTBC let me know if this is what you want and I will go ahead with it.

**Comment by ljramones** [comment]
ok, I did it that way and it seems to work.
