### ISSUE TITLE
Problem with side-pane "Objects in view" 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#261]
Two parts you can split them if you want. 

1. They are not in alphabetical order.  They really should be. 
2. There is no way to search that list.  If it has a couple of thousand stars in it, it's useless without a search.  Would it be possible to put a search box in that tab above the list?  If not, ok, because just dragging up and down a sorted list would work.  A disordered list, not so much.

**Comment by ljramones** [comment]
I sorted the list so that each plot has the star names in natural order.
I'll add a separate item for putting a search dialog with autocomplete
