### ISSUE TITLE
Algorithm for choosing what names to display has problems

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#262]
Choose any dataset and crank the radius out to 50 or 70 ly or more, and ALL the named stars are in the central third or less.  

Even if we restrict the central 70 LY to F and G stars, you get a total of 2 names in the outer half. 

Oddly, if you grab the 270 LY set, and restrict it to just O and B stars (600 or so) out to 270 LY, the names ARE distributed well.  

We need to increase the value of "distance from the center of the plot" by some amount. 

On a closely related note, and thus the same issue, I think that "number of names to display" needs to be a value in settings.

**Comment by ljramones** [comment]
number of names to display is in the settings.

Check the stars preferences section.

**Comment by BoatrightTBC** [comment]
Ahhh.  I missed that

**Comment by BoatrightTBC** [comment]
But we still need to tweak the distance component somehow to avoid the "all the stars cram up in the middle" problem.

**Comment by cegannon1** [comment]
Max # of stars to display has been  limit in BOTH  of the star display algorithms I put forth. I even indicated how many CHV showed, and why.

I also explicitly indicated that the only reason I did not  declare a hard limit was b/c that was putting the cart before the horse. But there HAS to be a limit.

Consider searching for G  V stars and then displaying. The are ALL going to have extremely high values.

20 or 30 tops has been my ballpark suggested beginning limit/total of diplayed star names (  see the original spreadsheets I sent ) from the start. But there was no way of knowing if that was optimal before seeing it.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Rick Boatright ***@***.***>
Sent: Sunday, March 21, 2021 1:12:55 AM
To: ljramones/trips ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ljramones/trips] Algorithm for choosing what names to display has problems (#262)


Choose any dataset and crank the radius out to 50 or 70 ly or more, and ALL the named stars are in the central third or less.

Even if we restrict the central 70 LY to F and G stars, you get a total of 2 names in the outer half.

Oddly, if you grab the 270 LY set, and restrict it to just O and B stars (600 or so) out to 270 LY, the names ARE distributed well.

We need to increase the value of "distance from the center of the plot" by some amount.

On a closely related note, and thus the same issue, I think that "number of names to display" needs to be a value in settings.

**Comment by cegannon1** [comment]
Agreed. That was bound to be the tricky bit.

Diminish range value.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ljramones** [comment]
There is a max number for labels in the star preferences dialog where you pick size and color of stars.

**Comment by cegannon1** [comment]
What is the default?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ljramones** [comment]
the default is 30.

![CleanShot 2021-03-21 at 17 48 47](https://user-images.githubusercontent.com/226595/111921952-b94f9180-8a6d-11eb-8df6-6ab33840835d.png)

**Comment by BoatrightTBC** [comment]
This has been subsumed by #259 and probably can just be closed.
