### ISSUE TITLE
Select stars from current dataset should auto-dismiss

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#263]
Once the "astrographic pop up box" has come up and tells me that it's plotted or selected some number of stars, once I click OK on that, the selection dialog box should dismiss. This is ESPECIALLY true if I told it to plot. I want to see the plot, not stare at a form I already ran.

**Comment by ljramones** [comment]
you mean the query dialog?

**Comment by ljramones** [comment]
done
