### ISSUE TITLE
Wording on initial dialog box

### ISSUE THREAD

**Issue by celebrith** [ljramones/trips#264]
**Describe the bug**

The initial Terran Interstellar Plotting System dialog box says:
_Use "Star Data/Load data set" to choose a dataset._

However, the Star Data menu in 0.6.7 does not have a "Load data set" menu item.  

**To Reproduce**

Run the ./runme.command

**Expected behavior vs Actual**

Expected instructions to match menu item(s) presented

**TRIPS version** 
- [ ] 0.52 
- [ ] 0.53
- [ ] 0.54
- [ ] 0.55
- [X] 0.6.7
 
**Desktop (please complete the following information):** 
 
- [ ] IOS 
- [ ] Windows 10 
- [ ] Windows Vista, 7 or 8
- [ ] Windows XP 
- [ ] Linux (add distribution and version to this line) 
- [X] macOS Big Sur 11.2.3 (Apple Silicon running in Rosetta 2) 

**Additional info **

Suggestions:

The equivalent seems to be:
_Star Data/Import data set from a file..._

Although that's not a "one button" option.  I'm almost thinking that we should revise the dialog box to something like:
_Please import a dataset (Star Data/Import data set from a file..."_
Or, maybe we could have a check to see if a dataset exists in the database, and if so, change the wording to:
_Please use "Star Data/Select Active Dataset..." to activate the desired dataset before plotting._

Alternative:
_Please follow the documentation to import and active a data set before plotting._

**Comment by ljramones** [comment]
done
