### ISSUE TITLE
Center star's name doesn't rotate with view like all other stars do. 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#267]
So, when you re-center on a star, the star's representation switches to a cube... which is all good. 
And the name flashes at about 1 Hz to indicate it's "highlighted"  and the font-size is doubled.

However, apparently when Larry coded the names to stay facing the viewer, he missed coding the name for the center star to also stay facing you so, it gets out of line...

Please fix. 
![image](https://user-images.githubusercontent.com/20006248/111940862-c7b5a180-8a9d-11eb-96d1-674e9f7c1c55.png)

**Comment by ljramones** [comment]
fixed
