### ISSUE TITLE
UI issues in manual routing 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#269]
The following extended from Joe Warum's notes: 

#### Image to refer to for part 1 issues:  
![Manual Routing - image 1](https://user-images.githubusercontent.com/20006248/112063512-82da4b00-8b2f-11eb-9324-b0182ac7b381.jpg)

- Joe complains that "It would be interesting to see the distance from last star in route when looking at the next one."
    -  Actually, the program DOES display that, but it's stated next to each step's segment, and is in the same color as the route. See screenshot -- parts labeled in green. 
    - It would be nice if the length info in the display (circled in green) was presented with a colored background.  -- White if the net color sum (r + b + g) is < 384, dark grey if color sum > 384 
- When you "continue route" to the third star in the route, the route from star 2 to star 3 does not plot in the right color. When I did it, that route segment plotted in black.  See segment highlighted in yellow above. 

#### Image 1 for part 2  -- This image is just after re-centering after creating segment two. 

![Manual routing no 2](https://user-images.githubusercontent.com/20006248/112064018-4eb35a00-8b30-11eb-97f6-d7682302ec21.jpg)

and, if I then re-center again on something else -- the route disappears completely from the screen even if I toggle routes on and off 
![Routing after recenter](https://user-images.githubusercontent.com/20006248/112064912-bd44e780-8b31-11eb-9c09-e11a472780ee.jpg)

#### Part three	

- Currently, nowhere on the screen can I see what stars are in my manual route.  Even if I open up the sidebar, and tell it to edit-route, the stars in the route are not listed.  

![Routing after recenter](https://user-images.githubusercontent.com/20006248/112065660-08abc580-8b33-11eb-8b8d-9ce33540c43b.jpg)

- Apparently, while I'm building a route, the route's lines are drawn as cylinders...  apparently lit from above-right, and this may be why sometimes the cylinder fades out of view in the image above.  I don't get to see it because it's poorly lit. 
![Route Big Lines](https://user-images.githubusercontent.com/20006248/112065776-44468f80-8b33-11eb-9c84-e0f0c0b425f2.PNG)

- But then, when I finish the route, the big easy-to-see cylinders disappear, and I get hairlines, no matter how wide I tell it to draw the route lines.  
![route small lines](https://user-images.githubusercontent.com/20006248/112065866-68a26c00-8b33-11eb-9735-88a885ee3a6d.PNG)

- So, if I tell it the route width is 15 (which is silly) I get really big cylinders... 
![really big lines](https://user-images.githubusercontent.com/20006248/112066236-fd0cce80-8b33-11eb-9412-cfa735a5054a.PNG)

- But then when I finish, the route collapses to a hairline. 
![line collapse](https://user-images.githubusercontent.com/20006248/112066293-14e45280-8b34-11eb-93ee-9b46dab10184.PNG)

#### Proposed solutions

- Ensure route continues to display during route building, even if we've done zooms, rotates, **or recenters**
- Provide contrasting background to segment length annotations. 
- Fix lighting problem on cylinders, it's cool because we get a 3-d sense from them, but the shadow intensity needs to reduce
- Fix rendering of finished routes to pay attention to width -- not the whole cylinder thing, but if I want 2 or 4 or even 6 pixel lines, I ought to get them 
- Add star names to the notes for the route as stars are added to the route, and include segment length I.E.: 
    - Sol - Start 
    - Alpha Centari - 4.7ly 
    - Mumble Fritzy - 7.4ly

**Comment by ljramones** [comment]
so far:  
<img width="839" alt="CleanShot 2021-03-23 at 21 11 30@2x" src="https://user-images.githubusercontent.com/226595/112239176-5fd99500-8c1c-11eb-8dc3-d5facfaf4bf9.png">

still working

**Comment by ljramones** [comment]
@BoatrightTBC when you are talking about recentering and plots disappear. Did you finish the route first?
The reason that I ask is that the route is not stored in a DB until you finish it. It is tentative.
When you recenter, it is actually a more that just a move. It actually has to go to the database and do a fresh query.
Doing a fresh query means that I have to figure out the bounds of the stars as 6 points (+/-x, +-y, +-z). Then I have to do an affine transformation on every point to do the plot. This cleanups all the in memory spots.

If you want to have a moving scratchpad of trial routes (not saved), I can do that, but its a new thing.

So just so you know, a recenter is like a brand new plot

**Comment by ljramones** [comment]
@BoatrightTBC  carrying on from the last, if this is what you want, then please file a fresh issue so I can do that as an add-on

**Comment by ljramones** [comment]
@BoatrightTBC and another thing is do we want to force the plot to show all the routes?
Here is what that means
- I only plot a route if I can plot all the segments.
- if we want to always plot all the routes, then I has to force the plot to use the bounds covered by the stars
- -also if a star is not part of a route, then I don't plot the route.

This leads me into a question on partial routes.
- do we want to plot a partial route based on above?

So what does that mean?
- if some of the stars are not part of a query, do we plot the partial route?
- a route could look disjointed.
- a route may appear on the side but not be present at all in the view
- you many see multiple disjoint routes but see only one in the side panel.

**Comment by BoatrightTBC** [comment]
The question about re-centering wasn't mine.  I'll go back to who raised it. 

Re drawing routes with legs off screen...  IdaNo.  Let's ask "the guys" (and Kim)

**Comment by ljramones** [comment]
ok, I think I have everything in that you wanted
partial routes are a question (recentering means wiping out a partial route)

**Comment by cegannon1** [comment]
Question, if you click on the  Partially  Visible route, What happens?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ljramones** [comment]
the question was do we plot partial routes (routes where some of most of the star are not in the screen plot currently)

I sort of wanted to know if we only plot the route when all the stars are available or plot even if they aren't.

So if we plot a partial route, is that confusing to someone?

**Comment by cegannon1** [comment]
I understand. But is there any ability to interact with the partially seen route?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ljramones** [comment]
sure, just need a definition of what you would expect and what is acceptable.

**Comment by cegannon1** [comment]
Rick, come in on this.

My gut tells me that the best thing from a user perspective would be able to simply click on the link and, if you accept action in spite of a warning that it's going to recenter or otherwise reconfigured the display, that you would get to see the whole route by having the My gut tells me that the best thing from a user perspective would be able to simply click on the link and, if you accept action in spite of a warning that it's going to recenter or otherwise reconfigured the display, that you would get to see the whole route.

Obviously comment that means an automatic change to the display selection it would seem to me that the logical parameter for that would be defined by theStarting star, the ending star, and the one most outside of the Column of Space between them.

  Thoughts?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
