### ISSUE TITLE
Mouse wheel zoom

### ISSUE THREAD

**Issue by MHaroldPage** [ljramones/trips#27]
It would be good to be able to use the mouse wheel to zoom - this is standard for video games.

**Comment by BoatrightTBC** [comment]
Yep, it is.  I'ld put it in the priority tier below dealing with database issues, pretty much because we sort of halve to in order to be able to support writing stories.  We need the UI for all that "extra" information (polity, race, population, resources, etc. ) first.

**Comment by ljramones** [comment]
got this working
ready for release v0.5.3
