### ISSUE TITLE
Problems when exporting from "Select Stars from dataset" form. 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#273]
When you check the "export to excel" box and click "run query" a new dialog box asks you for export type, but the ONLY option is CSV. 

I'm ok with that if it's what we want, but we should change the parent dialog's caption on the "export to excel" checkbox to just "Export Selected Stars" 

and then remove the csv option from the child dialog since it's ALWAYS going to be a CSV. 

The ADVANTAGE of excel files is that they're compressed, essentially as small as zipping a csv, but that's probably not worth the effort. Let's just use csv and change the checkbox to "Export Selected Stars"

**Comment by ljramones** [comment]
ok, it turns out that exporting to excel has a huge performance impact. Its mostly the library I use.
I'll make this change

**Comment by ljramones** [comment]
ok, fixed
