### ISSUE TITLE
Plot axis are rotated from correct. 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#274]
As it is, when you bring up a plot,  +x is to the right, -x to the left.  All good.  

### BUT 

+z is "away from you" into the screen, and -z is towards you out of the screen.  

### that should be Y 

and +Y is **UP** and -y is **down** 

### That should be Z

**Comment by ljramones** [comment]
computer graphics coordinate systems work this way. For whatever reason, they decided this was what they all wanted to do.
In Physics the convention is Z axis is up.
In computer graphics, the Y axis pointing up is the more common convention.

so if you have a Point3D (x, y, z) then I'll have to swap y and z when I plot to get the convention you want to see.

I'll have to look at this carefully at every point I plot and make sure I get all the swaps correctly

Here is a write up on it.
https://www.scratchapixel.com/lessons/mathematics-physics-for-computer-graphics/geometry/coordinate-systems

**Comment by ljramones** [comment]
fixed this.
I plotted the grid on the z plane and then rotated the image to be oriented with z facing north and and the x-y plane as an angle of 30 degrees
