### ISSUE TITLE
Fresh install 404 Error on Sample Data Selection

### ISSUE THREAD

**Issue by jasonmacer** [ljramones/trips#276]
**Describe the bug**

When performing a fresh install of the 0.67.exe from BoatRightTBC  and you select the sample data file "Sample Data 270 LY Sphere" the download is returning a "404 not found" error

**To Reproduce**

Steps to reproduce the behavior such as:
1.) Start Installation
2.) At "Select Components" check "Sample data 270 LY sphere"
3.) Continue / Complete installation

**Expected behavior vs Actual**

Expected: Download sample data and complete installation,
Actual: Install fails with "download error: 404 not found"

**Screenshots**
![image](https://user-images.githubusercontent.com/24413841/112177541-06934680-8bc7-11eb-87ef-af690c409a8d.png)

![image](https://user-images.githubusercontent.com/24413841/112177490-f7ac9400-8bc6-11eb-9952-6336a3818ce8.png)

**TRIPS version** 
- [ ] 0.52 
- [ ] 0.53
- [ ] 0.54
- [ ] 0.55
- [X] 0.67
 
**Desktop (please complete the following information):** 
 
- [ ] IOS 
- [X] Windows 10 
- [ ] Windows Vista, 7 or 8
- [ ] Windows XP 
- [ ] Linux (add distribution and version to this line) 

**Additional info **

**Comment by BoatrightTBC** [comment]
File name fixed.
