### ISSUE TITLE
Grid and Routes reappear oddly

### ISSUE THREAD

**Issue by celebrith** [ljramones/trips#277]
**Describe the bug**

If you turn the grid off and Recenter on a star, the gridlines (but not the numbers nor the legend) are redrawn even though the grid button is still turned off.  Additionally if you clear routes and then click the Plot Stars button or Recenter on a star, the routes are redrawn (as if they hadn't been cleared).

**To Reproduce**

Steps to reproduce the behavior such as:

1. Plot stars
2. Click the grid button to turn off the grid display
3. Click on a star and click Recenter on this star
4. And the grid comes back even though the grid button is still turned off
- Note that the numbers on the ends of the grid lines are still missing
- And the grid legend at the bottom is still missing
5. Click on the grid button, and the numbers and the legend are redrawn to match the grid that's already displayed

Also, if you click "Clear Routes" from the General Menu, the routes go away.  But if you click "Plot Stars", or if you Recenter on a star, the route lines are redrawn as if they'd never been cleared.

**Expected behavior vs Actual**

I expect the "Clear Routes" button to clear the routes both from the screen and from memory.  
I expect the grid button will turn off the grid and that behavior will persist across UI changes until/unless the grid button is turned back on.

**TRIPS version** 
- [ ] 0.52 
- [ ] 0.53
- [ ] 0.54
- [ ] 0.55
- [X] 0.6.7 
 
**Desktop (please complete the following information):** 
 
- [ ] IOS 
- [ ] Windows 10 
- [ ] Windows Vista, 7 or 8
- [ ] Windows XP 
- [ ] Linux (add distribution and version to this line) 
- [X] macOS Big Sur 11.3 Beta (20E5210c) (MacBook Pro) 

**Additional info **

**Comment by ljramones** [comment]
@celebrith I fixed the grid state so that if the grid is set to off then it stays off until you toggle it again.

but...

The clear routes and stars was a quick way to just clear it form the current screen. It doesn't clear them form the database.

When you recenter or replete, it actually queries the database again and that is what it redraws.
Do you want the clear routes to actually delete all the routes from the current dataset permanently?

**Comment by ljramones** [comment]
I remarked on this on the feedback slack channel
I'll leave this until then

**Comment by ljramones** [comment]
ok, I implemented a remove routes for the current dataset 

Its in
