### ISSUE TITLE
Allow revising parameters in the route finder if no route found

### ISSUE THREAD

**Issue by celebrith** [ljramones/trips#278]
**Is your feature request related to a problem? Please describe.**
When you use the Route Finder from A to B and it finds no routes, it just exits.  If you want to try different parameters, you have to start over.

**Describe the solution you'd like**
If the route finder fails to find a route, I'd like it to return to the previous dialog box, with the parameters still selected, allowing the user to adjust the parameters and attempt to find routes with the new parameters. 

**Describe alternatives you've considered**
I've been either taking a picture with my phone or noting down the parameters on a notepad, but I never really know if the parameters will work or not.

**Additional context**

**Comment by ljramones** [comment]
fixed
