### ISSUE TITLE
First dialog box missing "Republic"

### ISSUE THREAD

**Issue by celebrith** [ljramones/trips#279]
**Describe the bug**

When you load the program, you get the nice Cylon eye splash screen.  But then you get the first dialog to let a new user know that they must choose a data set, and the title of that dialog is "Terran Interstellar Plotting System".  It leaves out "Republic" and it was bugging me subconsciously that TIPS != TRIPS.  And I'm guessing that most people have clicked the "Don't show this at startup" and then don't see it again (I'm trying to avoid clicking anything to avoid showing me stuff so I'm getting the full user experience).

**To Reproduce**

Load program and not have checked the "don't show this at startup" previously

**Expected behavior vs Actual**

Not sure if we would like to add "Republic" to that screen (which will either make the title wider or split it onto two lines) or make some other change?

**TRIPS version** 
- [ ] 0.52 
- [ ] 0.53
- [ ] 0.54
- [ ] 0.55
- [X] 0.6.7 
 
**Desktop (please complete the following information):** 
 
- [ ] IOS 
- [ ] Windows 10 
- [ ] Windows Vista, 7 or 8
- [ ] Windows XP 
- [ ] Linux (add distribution and version to this line) 
- [X] macOS Big Sur 

**Additional info **

**Comment by ljramones** [comment]
done
