### ISSUE TITLE
Typing in the distance boxes in select stars does not update the slider position 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#281]
Typing a number in the distance box does not cause the slider to move. Several issues with that: 

- you can get one slider hidden behind another. 
- the program ignores the value you type and uses the slider position.  
  - Open trips, don't plot
  - go to select 
  - type 15 in the right hand box and tab to exit the box 
  - press select -- after plotting press dismiss. 
  - display shows a 20 LY selection
  -

**Comment by ljramones** [comment]
fixed
