### ISSUE TITLE
Remember last used dataset 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#282]
After the program has been started and a dataset successfully imported and made active, the program should remember what dataset was last active and on the next startup automatically activate that dataset and display the choice in the plot status display. 

This is PARTICULARLY useful if you have only imported ONE dataset. Why should I have to pick as active the only one there is?  

Although the more general case is also true.

**Comment by ljramones** [comment]
ok, more db changes :)

**Comment by ljramones** [comment]
want me to do a plot on start?

**Comment by ljramones** [comment]
ok, I added a replete of the last dataset
