### ISSUE TITLE
Activate dataset after import, sort of. 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#283]
After completing the "Add a dataset" dialog and successfully importing it, when the import is finished, 

- CLOSE the add-a-dataset dialog.  Why should I have to close it after it's finished? 
- Ask the user "Make xxxxxxxxxx the active dataset?" with yes and no buttons.  
- In either case, after answering yes/no, close the Dataset Management dialog box.  Yes, it's POSSIBLE that someone wants to import more, or export, or even delete after adding, but it's unlikely, and it's ESPECIALLY unlikely if they answered Yes to the "Make it active? question.

**Comment by ljramones** [comment]
adding a dataset automatically makes the last dataset the current context.

So I understand that you want to ask someone if they want to add a dataset and if they say no then it disappears and they see the data management dialog.

If they say yes, then its the add dataset

**Comment by ljramones** [comment]
ok, this question is messy.
Every add dataset request will ask you what you want to load. It gets the info closes and loads the dataset. 
The last loaded data set is automatically set to be the context


So you want me to then ask if you want to load more data and if I say no then colsew the data management dialog?

**Comment by ljramones** [comment]
ok, implemented as described
