### ISSUE TITLE
Route line width ignored when plotting searched for routes.  

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#285]
I did a search, and in the search I told the program the route line width should be 4  (pixels I assume, but anyway, 4 somethings)  I also tried 8 and 10.  In each case, the route plots as a hairline.  I, personally would like wider routes so I can see them, and in any event, the program offers it but doesn't implement. 

![Route Width](https://user-images.githubusercontent.com/20006248/112381213-54d44280-8cb8-11eb-912f-56d43c0d0744.png)

**Comment by ljramones** [comment]
working on this one now

**Comment by ljramones** [comment]
I've fixed this
