### ISSUE TITLE
Change user controls checkbox not persisting through program restarts. Also, name of that.  

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#286]
I have to go into display/Change App Pref/User controls and change the checkbox every time I start the program.  That should persist between starts just like colors etc does. 

Also,  I propose the following change the labels on that screen: 

![rotation controls](https://user-images.githubusercontent.com/20006248/112383406-13916200-8cbb-11eb-8f14-f786ec3e9b16.png)

**Comment by ljramones** [comment]
changed
