### ISSUE TITLE
Advanced search -- several problems 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#287]
- Dialog should default to current active dataset. Instead it defaults to whatever the first-loaded dataset was (or at least the top one in the list.
- Descriptions of the fields all say "actual mass of the star."  If we don't have time to actually create them before next release, can we blank the descriptions and just leave the name and field-type?
- Operators to use:  Currently, the text operators all have OPERATOR  TRUE -- and that's confusing even to me.  Two possible fixes (examples using 'LIKE':   
  - LIKE (True if operand matches a pattern) 
  - LIKE - True if operand matches a pattern 

Personally I like the first.(parens)

**Comment by ljramones** [comment]
I can update these descriptions. I have them in a file that is loaded

**Comment by ljramones** [comment]
ok, I made changes
I removed incorrect descriptions and corrected some.
I set the active dataset as the default dataset
the made the other changes you wanted
