### ISSUE TITLE
Advanced search: When results have few stars, grid gets weird. 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#288]
Starting from the Trips-normal-names-270 data, run the following advanced query: 

DISPLAY_NAME LIKE 'Gamma 02 S%' OR DISPLAY_NAME = 'Sol'

and you get this:

![weird grid](https://user-images.githubusercontent.com/20006248/112390120-ce256280-8cc3-11eb-9e47-09e9bb8444aa.png)

**Comment by ljramones** [comment]
I retested this and I was not able to reproduce on the version of code I have (after 49 fixes). I suspect that somehow I fixed it in another fix
