### ISSUE TITLE
after rotating the x-y-z axis to the astronomically correct position with z axis, the rotation drag with mouse is weird

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#294]
I believe that the default mechanism for roll and pitch was optimal for when the y axis was pointing up but now, it acting weird.

Needs to be fixed.

**Comment by BoatrightTBC** [comment]
Sorry that we broke that for you.  

You'ld think it wouldn't matter...

**Comment by ljramones** [comment]
You didn’t break it. It was the way it was coded.
I wasn’t happy with the way it worked and this gives me an excuse to fix it

**Comment by ljramones** [comment]
fixed. I mistakenly swapped the X and Y angles in the rotation
