### ISSUE TITLE
Star context menu and manual routing

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#297]
First, we propose to change the star context menu as follows: 

**Star Name**
- Highlight star 			          --- puts the 3d  Four pointed star over the star in the view. 
- Show Properties of this star	      ---  opens the properties tab in the side pane 
- Recenter on this star 			      
- Edit star 			              ---  opens the big edit star's data form.  
- Delete star			              ---  does two "Are you actually sure" questions, 
---------------------------			
**Routing**		                      < - - This line is not clickable…  
- Run route finder/generator
- Build route on screen by clicking stars   (See below for details) 
---------------------------
**Generate distance report from this star**

---------------------------
 (that's the end of the menu.  hard to do good menu examples in markdown) 

Then, when the user says they want to build a route by clicking, they're dropped into a "Make a manual route" mode. A small route info form pops up  and lets you choose name, color, width, etc..  

It's already filled in the start star that you clicked on, and then, just below it, on the form it says: "Click on next  star."  and you do.  and that star's name is added to the route info screen and the cursor jumps down a line and says "Click next star"  and you do, and you do, until you have them all selected, and then you press the "Finish Route" button and it saves that route and the route info screen closes.  

![manualroute](https://user-images.githubusercontent.com/20006248/113356231-8fb52680-9307-11eb-9a77-e4093409e11e.png)

**Comment by cegannon1** [comment]
This is probably already in the program, but the 3d pointed star should be colored as per the color reserved for the spectral type it now represents.

From: Rick Boatright ***@***.***
Sent: Thursday, April 01, 2021 5:33 PM
To: ljramones/trips
Cc: Subscribed
Subject: [ljramones/trips] Star context menu and manual routing (#297)


First, we propose to change the star context menu as follows:

Star Name

  *   Highlight star --- puts the 3d Four pointed star over the star in the view.
  *   Show Properties of this star --- opens the properties tab in the side pane
  *   Recenter on this star
  *   Edit star --- opens the big edit star's data form.
  *   Delete star --- does two "Are you actually sure" questions,

________________________________

Routing < - - This line is not clickable…

  *   Run route finder/generator
  *   Build route on screen by clicking stars (See below for details)

________________________________

Generate distance report from this star

________________________________

(that's the end of the menu. hard to do good menu examples in markdown)

Then, when the user says they want to build a route by clicking, they're dropped into a "Make a manual route" mode. A small route info form pops up and lets you choose name, color, width, etc..

It's already filled in the start star that you clicked on, and then, just below it, on the form it says: "Click on next star." and you do. and that star's name is added to the route info screen and the cursor jumps down a line and says "Click next star" and you do, and you do, until you have them all selected, and then you press the "Finish Route" button and it saves that route and the route info screen closes.

[Image removed by sender. manualroute]<https://user-images.githubusercontent.com/20006248/113356231-8fb52680-9307-11eb-9a77-e4093409e11e.png>

**Comment by ljramones** [comment]
I have the other items. 
Still need to work on routing changes and those are substantial

<img width="544" alt="CleanShot 2021-04-03 at 14 19 35@2x" src="https://user-images.githubusercontent.com/226595/113487732-b4380c80-9487-11eb-9a2a-87a5d71a6590.png">

**Comment by ljramones** [comment]
The reason why the "Routing" looks washed out is that you can only have menu items in this popup menu. You can't add anything else. 
So win order to make a menu item look like a label I have to disable any action on it to make it non clickable.

**Comment by ljramones** [comment]
The popup route form will have to be a dialog. I can't embed it in the canvas or it will be another 3d object and it will annoy the heck out of you.
I'll make sure that the dialog is non modal and is always on top.

**Comment by ljramones** [comment]
For this item "Run route finder/generator"
I have a question.

Do you mean the automated routing system (as opposed to the manual one)?
If so, then you want me to set the FROM point to be the star that you clicked on.
Do you want to have the TO point to be a selected star in the dialog or one that you click on the screen?

**Comment by BoatrightTBC** [comment]
Yes, the manual route maker has to be a dialog. In 067 you pop up a dialig to pick the color and name the route, so. We leave that up, and pick the stars to continue... 

Make the dialog as small as you can to leave as much plot as possible showing. 

Second... Yes, i ment to trigger the route finder - generator with the selected star as the first star. 

So, manual routes moving to a dialog, instead of being all in the context menu and found - search round routes able to be triggered from the context menu.

**Comment by ljramones** [comment]
so far. I have to design the two different dialogs.
for the automated one, we have the choice of specific star and polity filters as well form the existing functionality 

<img width="518" alt="CleanShot 2021-04-03 at 17 55 01@2x" src="https://user-images.githubusercontent.com/226595/113492520-e6f0fd80-94a5-11eb-842c-06354d07ebf1.png">

**Comment by ljramones** [comment]
ok, this is finally complete.
You can use the automated routing finding and manual route finding.
when either of these is actioned, it changes the click function so that it selects stars for either an end point for either finding stars from star a to star b. Or it draws a route segment from each
