### ISSUE TITLE
Details about highlight star

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#300]
When the program highlights a star by superimposing a Moravian star over the sphere, the Moravian star should be colored the same as the underlying star.  

> This moved from a comment Chuck made on Context menu and manual routing.

**Comment by ljramones** [comment]
using this to get it to blink.

**Comment by ljramones** [comment]
got the blink to work. It will pulse a Moravian star for 100 cycles and stop or until the user selects another star
