### ISSUE TITLE
Dealing with partial routes where some stars aren't in the current view. 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#301]
In talking to the Alpha's and to Chuck, it appears that there is a concensus that we want to display partial routes that extend off-screen.  If so, we need to decide what to display, and what to do with it. 

**What to display**

In order for part of a route to display, at least two stars in the route have to be in the view. While it is true that if one star is shown, it is sort of theoretically possible to have a line leading from that star off into nowhere, but for the present purpose, let's assume that at least two stars that are part of the route are in the view. There are two general classes of possibilities: 

- One end of the route (start or end) is in the view or 
- Both ends are outside the view with one or more central segment contained in the view.  

Either way, we need to be able to indicate that the route extends off-screen.  A line segment pointed off screen, and capped with a hemisphere or a cone would indicate that the line "goes off screen..."  like these two: 

![image](https://user-images.githubusercontent.com/20006248/113375702-95c1fc00-9335-11eb-89a7-f3917953a4be.png)

**What to do with the partial route**

If you click on the partial route, pop up a context menu with the following choices: 

    ****Route Name****
    Extend display to show full route
    Show route in side pane

The first choice re-queries the dataset and increases the view radius to allow all the stars in the route to display. 

The second choice opens the side pane if it isn't open, selects the routes tab, and scrolls to the selected route.

**Comment by ljramones** [comment]
@BoatrightTBC 
There is a third and fourth possibility. You might have a middle section missing and have the beginning and end segments.
You might even be missing the begging, have a section, then a middle section, have another section and be missing the end.
The fourth is  the most complex form of these variants.
Do you want to handle 3 and 4?

**Comment by BoatrightTBC** [comment]
Well crud. 3 and 4 suck. 

3 and 4 would require multiple arrow ends..   uhn. 

I know its complex. Is 3 and 4 TOO complex? Are we reaching "oh God shut up Rick"  or is it doable?

We can take the time we need...  we're not on a schedule.

**Comment by celebrith** [comment]
This is something that I found confusing - If I change the view so that one or more stars in a route aren't in the view, the entire route disappears - but then reappears when you include the stars again.  So I'd be in favor of a solution.
Would it make sense to have a partial route show as a dotted line rather than a solid, so that you realize that the route exists but not all of the stars in the route are displayed?  Not sure if that's possible / easier / harder than having an arrow on the end of each part of the route that terminates "off screen"

**Comment by ljramones** [comment]
@celebrith 
That was as designed. When I plot the stars requested form the query, I have the set of routes.
I do a check that all the stars are present for each route. If the stars are all present then I plot them. If not then they aren't plotted.
The reason I didn't was that I didn't have a clear idea of what to do if stars were missing. People would think that something was wrong.
Now that we have a definition of what to do then I can proceed.

**Comment by ljramones** [comment]
moved to next version

**Comment by ljramones** [comment]
done
