### ISSUE TITLE
Using color to identify a route and link the side pane to the star-view pane. 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#302]
In the post about the changes done for 0.6.8 in manual routing, Larry posted an image of the improved side-pane display of a route.

![image](https://user-images.githubusercontent.com/226595/112239176-5fd99500-8c1c-11eb-8dc3-d5facfaf4bf9.png)

In order to clarify which routes on screen correspond to which routes in the side pane, draw a line of that routes color over the route name like this: 

![image](https://user-images.githubusercontent.com/20006248/113376921-85f7e700-9338-11eb-929e-04aab4724480.png)

Because the side-pane is a piece of text to display, you can't just DRAW a bar there, but you can do a line of spaces or non-breaking spaces, or even hyphens with the foreground and background colors both set to the color assigned to that route.

**Comment by ljramones** [comment]
I use a ListView, which is just a set of strings. 
http://tutorials.jenkov.com/javafx/listview.html

I'll have to use another component to display in order to do this.

**Comment by ljramones** [comment]
I couldn't do that but I did this instead.

What it additionally gives you is a local control to immediately see and change the color. You can also hide or show any given route

<img width="1071" alt="CleanShot 2021-04-13 at 09 27 10@2x" src="https://user-images.githubusercontent.com/226595/114560198-7468e600-9c3a-11eb-908c-881e678361c4.png">

**Comment by ljramones** [comment]
the color picker allows you to set any color you want. I short-circuited the color change so you can try a variety of colors very quickly.

**Comment by cegannon1** [comment]
Great. I am recommending black on light gray as the default. Let’s try a test with the numbers in bold face.
