### ISSUE TITLE
Side column button(s) nonresponsive

### ISSUE THREAD

**Issue by cegannon1** [ljramones/trips#31]
On some invocations of the program, choose the Settings option. Choose the first option and load a dataset.  Objects in View option (immediately below the dataset option) was unresponsive. Restarting the program fixes. Another start and it is broken again. Cannot detect pattern. 

Image of failpoint attached.
![unresponsive button s](https://user-images.githubusercontent.com/69170614/91644694-8fb91500-ea0c-11ea-94e7-64fdf26addbd.png)

**Comment by ljramones** [comment]
I will look into it

**Comment by ljramones** [comment]
this should be fixed now
