### ISSUE TITLE
Update buttons in dialog boxes

### ISSUE THREAD

**Issue by celebrith** [ljramones/trips#310]
**Is your feature request related to a problem? Please describe.**
When we have a single button to dismiss an informational dialog, we should use a single consistent word.
I suggest using "OK", which is generally used across many programs.
We have some using "Cancel" and others using "Dismiss" currently.

Also, to avoid opening a second issue, can we change the dialog box for the SQL Examples (from the Advanced Query Dialog) to have "SQL Examples" in the title of the box rather than a blank title and the "SQL Examples" inside the box?  That would be consistent with other dialog boxes in the program.  See 2nd screen shot.

**Additional context**
![2021-04-03_23-08-42](https://user-images.githubusercontent.com/8394790/113497577-74971200-94d3-11eb-8bb1-dceb2370a6b9.png)
![2021-04-03_23-18-30](https://user-images.githubusercontent.com/8394790/113497583-7bbe2000-94d3-11eb-9ed3-b80ceb7de338.png)

**Comment by celebrith** [comment]
Crud.  Forgot the other part.

Would like to change the buttons in the Advanced Query dialog to match the others in the program.
Show examples (or Show Examples), Run query (or Run Query), and Dismiss.

We probably should make a design decision on how we handle multiple word buttons - Do we always capitalize each word, or do we always only capitalize the first word?

![2021-04-03_23-28-23](https://user-images.githubusercontent.com/8394790/113497682-4cf47980-94d4-11eb-920c-bbad6127812c.png)

**Comment by ljramones** [comment]
CRUD (CREATE, RETRIEVE, UPDATE, DELETE)? :)

**Comment by ljramones** [comment]
fixed
