### ISSUE TITLE
Update display elements in the Astrographic Records Table

### ISSUE THREAD

**Issue by celebrith** [ljramones/trips#311]
**Is your feature request related to a problem? Please describe.**
The title for the Astrographic Records Table is a bit confusing with extra : 
In the screenshot, I'd rather see "Astrographic records table for dataset:"

Also, would like to see "Distance to Earth(ly)" changed to "Distance to Earth (LY)"
The first one I keep reading as "Earthly"

**Additional context**

![2021-04-03_22-52-27](https://user-images.githubusercontent.com/8394790/113497621-da839980-94d3-11eb-886b-87dfde3fb2cb.png)

**Comment by ljramones** [comment]
fixed
