### ISSUE TITLE
No range limit parameters available when generating route

### ISSUE THREAD

**Issue by cegannon1** [ljramones/trips#32]
**Describe the bug**
No range limit parameters available when generating route

**To Reproduce**
1. Go to star display
2. Click on star to start route from
3. Scroll down to start route
4. Choose another star
5. Scroll down to continue route and click
6. Route appears as a simple connector between the two points.
7. No option to limit distance per shift/leg of route. 

**Expected behavior**
At some point prior to choosing a route, a shift/distance limiter needs to be offered to the user. This may be more complex to operationalize that a simple choice of range per route. See remarks.

**Screenshots**
First screenshot shows beginning of process of creating a leg of a route. Second shows the completion. At no point is a range limit option offered. This is a crucial component.

**Additional context**
Looking forward, a sublist of needs to match the MPV metrics:

1) a range limit option. Optimally, there might be a max AND a min (some FTL drives might have that requirement)
2) We do not have polity's yet, but they become important. Different interstellar states will have different maximum (an maybe minimum) ranges. So that a user does not have to remember the actual range, there should be an option which allows them to choose a "polity shift performance" option when creating routes. With that they can shift back and forth between different range limits at the touch of a button. At the very least, there should be a handy pop-up that presents a "performance index" of the polities recorded in the dataset. 
3) It is important to leave old ranges for old routes unaltered. In short, let us say route A was established when the shift range max was 6.5 LY. Then we reopen the dataset to add more information when time has passed and the new polity max shift range is 8.3. The old routes must NOT be automatically updates, since old starships with the old ranges may still ply those routes. 
4) routes should not just have color choices, but line thickness (allowing the user to signify importance not just by color code but "boldness".

I do not know if any/all of this are features that have not yet been activated, but it seems prudent to put these waypoints out clearly now.
![Star label focus degradation when proximal](https://user-images.githubusercontent.com/69170614/91645068-f855c100-ea0f-11ea-9190-efa191f7d33f.png)
![Route responds to color choice but has no range limiter](https://user-images.githubusercontent.com/69170614/91645070-fdb30b80-ea0f-11ea-9e73-6ed016d39b51.png)

**Comment by ljramones** [comment]
I haven't started in these yet.
I am working through all of this phase by phase. 
The amount of steps is huge and I have to be careful adding the functionality
Expect to see it piece by piece. 
There are literally thousands of line of code associated with this.

**Comment by cegannon1** [comment]
Understood and appreciated. Unfortunately, my ignorance of programming makes it impossible for me to anticipate at what point in the design process it becomes advisable vs. necessary vs. too late to raise a topic that might go overlooked. Hence, as I call it, this calls attn to a "waypoint": doesn't matter when it happens. Just that it does.😁

**Comment by ljramones** [comment]
I'll put that stuff in. probably in the next release after this one v0.5.3

**Comment by ljramones** [comment]
I have this one done. You will have to look and tell me if its what you want
