### ISSUE TITLE
load new graphical objects into system

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#327]
we have a couple of new graphical mesh object to load into the system

this task covers them

**Comment by ljramones** [comment]
translated the object from OBJ to FXML
separated the FXML into 9 separate objects
stored into the resources folder
wrote factory methods to load them
now waiting for a purpose of these objects

**Comment by cegannon1** [comment]
One of these will be the other map marker for polities.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ljramones** [comment]
Ok, let me know which you want and I’ll set it up

**Comment by ljramones** [comment]
There are 9 objects in the OBJ file.
