### ISSUE TITLE
Star Properties Report

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#328]
A new report was requested called Star Properties and I need to understand what his is

**Comment by ljramones** [comment]
this is mapped to a warning that it isn't implemented

**Comment by ljramones** [comment]
moved this to the v0.7.0 release since it is not defined

**Comment by ljramones** [comment]
No one responded so I can cancelling this feature

**Comment by cegannon1** [comment]
Who was the source of this request?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ljramones** [comment]
I couldn't find anything about it.  It might have been Rick or one of the Slack people.
I'll reopen if someone tell me what its supposed to be.
