### ISSUE TITLE
Use objects in view star list to go to star

### ISSUE THREAD

**Issue by cegannon1** [ljramones/trips#33]
**Is your feature request related to a problem? Please describe.**
This is not a problem in the program, but in image density. Specifically, stars become needles in haystacks the more zoomed out the view. Need a way to find them, particularly those that are small and not showing label(s).

**Describe the solution you'd like**
When in Objects in View, click, double click, or CTRL+click on any entry. the program takes you there, so it is the closest object in view. Should not automatically recenter...that is easily accomplished by clicking on the star icon and requesting that function from the scroll-down menu of options.

**Describe alternatives you've considered**
One could look at ALL the stellar records instead of Objects in View. But that is not really an alternative. That should be another feature. I explain below.

**Additional context**
Stars as needles in a star-field haystack is a major challenge. Almost every program addresses this by giving the user two "hound dog" options, where you choose the star from a list and the program puts your PoV there. Does not recenter automatically, because you may ultimately want to return to your original view after checking some data or etc. 
These lists usually are at the "objects in view" equivalent function. Or at the "all objects in this dataset option". There are good reasons for each. The objects in view allows you to find a small/unlabeled/crowded-out star in a confused pack of other icons. Very helpful for a variety of tasks. Example (common): you are not using an automatic route generator, but are hand plotting one for a variety of possible reasons (avoid enemy turf, link green worlds, etc.). You already have a basic idea of what you want, because you have pulled "star distances" from under the Reports family of options. 

Problem: half of the stars you want to go to are not labeled and are not large or bright icons. but you know they are in view. Being able to go back to Objects in View and find them is a HUGE help.

Now imagine you are looking at a HUGE starmap: hundreds of objects, routes displayed, etc. You need to find one start in that. Well, you COULD zoom all the way out and use the Objects in View function. But again, you might not want to be giving up a closer and important position/center in that huge furball of objects. So being able to choose the unfindable star from a list of all objects in the DATASET is really useful.

In the screenshot
![feature wanted--discover star location through Objects in View list](https://user-images.githubusercontent.com/69170614/91645403-ca25b080-ea12-11ea-92a3-c370ce8125cc.png)
 below, I can't find Proxima Centauri. I have chosen it on the Objects in Display option. How convenient if I could just click on it. 
(and to reverse just requires a "back to center" command/option)

**Comment by ljramones** [comment]
hi Chuck I think I have this implemented the way you want now. 
You will see it in v0.5.2
Stars in the list on the side panel will show in alphabetical order and you can choose to 
a) select(click) on a star to show its properties.
b) you can select to recenter on a star from this list
c) edit any of the stars in the list

take a look at v0.5.2 when I release it and tell me what else you want or is it enough.

**Comment by ljramones** [comment]
I also added a highlight feature in v0.5.3 (not yet released) which will allow you select a star and see small rotating version of it in the display.

I added dialog under search menu to use an autocomplete to see the list of stars in view and as you type, the list becomes narrower. Selecting on go to will hight this one.
