### ISSUE TITLE
Catalog query

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#331]
add search by catalg id choice under the other searches.

**Comment by ljramones** [comment]
is this related to a partial search in the catalogid field. 
How do you want to add this query?
Do you want to add it to the big query pane (the one where you select star type and port type etc.)
Do you want a separate query? I could add this but how do you want to describe the menu text for it

**Comment by BoatrightTBC** [comment]
No, this is seperate and super simple.

Menu:  Find a star by a catalog ID.

Takes a text value, searches through the catalogids, and returns the display name of the star.

Return some text like:  The usual name for "IP 207345" is "Gamma Sillius 42"  Use that when searching or building routes, etc.

the only option is "return partial matches"  so that if I enter  "L 1151"  it returns

Catalog ID                    TRIPS NAME
L 1151-5                       Alpha Sillius
L 1151-a                       Beta Sillius

etc.

return partial matches should be a checkbox.
________________________________

**Comment by ljramones** [comment]
done
