### ISSUE TITLE
Changing Star Radius has no effect

### ISSUE THREAD

**Issue by MHaroldPage** [ljramones/trips#333]
**Describe the bug**

Edit > Preferences > Stars, changing Radius (sol units) and clicking Change has no effect.

**To Reproduce**

Edit > Preferences > Stars, changing Radius (sol units) and clicking Change has no effect.

**Expected behavior vs Actual**

I would expect changing the radius to change the visible size of the globes on the main 3D display.

**Screenshots**
**TRIPS version** 
- [ X] 6.8
**Desktop (please complete the following information):** 
 
- [ ] IOS 
- [X] Windows 10 
- [ ] Windows Vista, 7 or 8
- [ ] Windows XP 
- [ ] Linux (add distribution and version to this line) 

**Additional info **

**Comment by ljramones** [comment]
you have to replot to enact the change. The setting is just a persistent change. All the settings on preferences require a replot

**Comment by ljramones** [comment]
This one works as specified. Make a change and replot
