### ISSUE TITLE
Tools > Links should be Tools > Transits

### ISSUE THREAD

**Issue by MHaroldPage** [ljramones/trips#334]
**Describe the bug**

Tools > Links should be Tools > Transits

Links and Transits are used interchangeably in this menu.

**To Reproduce**

Tools > Links 

**Expected behavior vs Actual**

Consistent terminology.

**Screenshots**

If applicable, add screenshots to help explain your problem. If none, delete this section. You will have to have saved screenshots to your local drive, then just drag and drop them to here in the editor. 

**TRIPS version** 
- [X] 6.8

**Desktop (please complete the following information):** 
 
- [ ] IOS 
- [X] Windows 10 
- [ ] Windows Vista, 7 or 8
- [ ] Windows XP 
- [ ] Linux (add distribution and version to this line) 

**Additional info **

**Comment by ljramones** [comment]
Changed Transits button to Links as they decided that Links is prefereable
