### ISSUE TITLE
Add missing stars to catalog

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#341]
Sol and 55 Tauri are missing from the catalogues.

Add them

**Comment by jimmeeksjohnson** [comment]
Hey. IDK what 55 Tauri is or if this will be helpful, but FYI, I merged the 70LY excel file with the 50 brightest stars. 8 out of 12 within 70LY were missing. I left the ones farther than 70LY in the file in case you can use them. Data source Hipparcos Mission.


[70LY Base dataset - merged ss.xlsx](https://github.com/ljramones/trips/files/7875805/70LY.Base.dataset.-.merged.ss.xlsx)

**Comment by ljramones** [comment]
Thanks, that will be helpful. I know that Chuch is interested in getting a star wrangler to take over the catalogue work now that Rick isn't here.

I noticed that you replicated the spectral type in the radial velocity column.
I think we need to start a separate project to sort out the star catalog.

**Comment by jimmeeksjohnson** [comment]
oops -- I'll save further comments for now so you can focus on the release and establish a better venue when you have time.

**Comment by ljramones** [comment]
Hi,

I’m thinking of starting a new Github project for the catalogs. That way, we can manage it separately

**Comment by jimmeeksjohnson** [comment]
That sounds great. Would it make sense to set it up with a master db of all
stellar objects we care about in the proper format and a script to extract
subsets like 30LY, 70LY for release?


Jim



Author of the Entangled Galaxy Series
<https://www.amazon.com/Enemy-Immortal-Space-Adventure-Thriller-ebook/dp/B07NJVWJPB>
.
Visit me at Meeks-Johnson.com or Amazon Authors
<https://amazon.com/author/jimmeeksjohnson>.

**Comment by ljramones** [comment]
I think that concurs with what Chuck, Rick and I had in mind.
I responded on Facebook (more for visibility to the group) on an idea of building this capability into TRIPS as a one-stop shop.
That way, trips can be used at different experience and expertise levels

**Comment by ljramones** [comment]
Sol and * 55 Tau are added
