### ISSUE TITLE
No Delete or Backspace Option When Generating Routes on Screen

### ISSUE THREAD

**Issue by HiverLord** [ljramones/trips#392]
**Describe the bug**

When generating a route by clicking on star systems on the screen, there is no backspace or remove system option, for when a system is accidentally added/clicked into a route.

**To Reproduce**

Tools
Route
Create Route By Clicking On Stars

**Expected behavior vs Actual**

There should be an option to remove a star/the last star entered, from the route being created.

**Screenshots**

If applicable, add screenshots to help explain your problem. If none, delete this section. You will have to have saved screenshots to your local drive, then just drag and drop them to here in the editor. 

**TRIPS version** 
-[x]- v0.7.1
 
**Desktop (please complete the following information):** 
 
- [ ] IOS 
- [X] Windows 10 ACTUALLY WINDOWS 11
- [ ] Windows Vista, 7 or 8
- [ ] Windows XP 
- [ ] Linux (add distribution and version to this line) 

**Additional info **

**Comment by ljramones** [comment]
added a remove last segment button.
