### ISSUE TITLE
propagate Star display preferences based on view preferences

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#43]
There is a dialog to chose star display and other aspects of a star.

At the moment, changing this doesn't affect the actual display because the parameters are chosen on db file load.

we need to add a parameter to make the change easy in the db because the actual graphics know nothing about stars.

**Comment by ljramones** [comment]
this doesn't make much sense because of how we load data so won't fix

**Comment by cegannon1** [comment]
Can't fix?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ljramones** [comment]
this was for this screen
![image](https://user-images.githubusercontent.com/226595/92672269-4c9d5280-f2e6-11ea-835c-ffcc36c36cc0.png)
It doesn't make any sense to do this.
The reason is that we read real data and those setting are set on the initial read of the file.
The radius (size of the star) is determined on the initial read. So if we change it here then what does the actual size in the database actually mean?

As for the color, this is set from the initial read (for CHV, that was read from a file). I could not put in a color and then assign it on the plot form this table.

I can resurrect this bug report, but I would want to know the policy as stated above.

**Comment by cegannon1** [comment]
Oh, this. Yeah
Frankly, I'd say keep the star colors set.

Major concerns are some color choices. O and B should be light blues. The current colors will not read against the background.
F wants to be yellow enough that you know you are not looking at white when a star is on the other side of the grid.

Suggest all objects beneath M get a dull violet.

Not sure about radius scaling. May be more dramatic than optimal, but can't tell until we see a full field with all names facing, and various stellar separations (i.e. up-to 5 LY) displayed as lines with distance markers.

Hard to know how cluttered that view will be with these settings. If they currently follow CHV, then we have a benchmark. If not, it's too early to say.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
