### ISSUE TITLE
Grid Calculations appear broken  Part 2 -- grid does not match selected data. 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#49]
- Clear the database 
- Load the 50 ly data set and plot it (incorrectly, see previous issue) 
- load the 150 LY data set and plot it (incorrectly, see previous issue) 
- go to query.  Select the 150 LY data set.  Slide range slider all the way to the right -- 150 LY 

Grid now has lots of stars (good) but grid didn't change, still has 20 ly radius and caption says 1 grid = 5 LY 

Also, just guessing, but it doesn't look like it actually plotted what I queried.  There just aren't 7000 stars in the display at that point.  I think it's still displaying the 50 LY data, although it's now displaying all 50 LY not the central 20.

**Comment by ljramones** [comment]
will be fixed in Redesign how the gird actually works #65
