### ISSUE TITLE
UI problem with sorting a table of stars to edit. 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#53]
We've been told that in 0.53 when the edit table of stars comes up, it will now be sorted in Star-name order, which is good. 

In order to keep the program responsive, the table of stars is paged in units of approximately 50 stars.  We've been told in 0.53 there will be a page number shown on the screen so we can know how far down we are in the response. 

The table display supports clicking on the column headers, so we can sort by any column ascending or descending. 

HOWEVER, clicking on the column header only sorts that page, not all pages.  Consider the following situation:  We query for all the stars within 50 LY of sol, but we're really only interested in the stars in the range of 45 to 50 LY.  We do a query, and display the table, and we get all the stars sorted by name.  Now, we click on the "distance to earth" column twice, the first time showing the closest stars, the second time the farthest, but the farthest stars it lists are only 32 light years away!!!  Why? because the sort only sorts the DISPLAYED PAGE.  Not only that, but if you then go to the NEXT PAGE, that page isn't nessesarily sorted the same way. 

Now, we could ask that the system just provide min and max values in the query for distance, but what if we want to sort by radius? or by Z distance above the galactic plane? (I don't know why you would want to do thagt, but I guarantee someone will.) 

It seems clear that when sorting the multi-page table, the system needs to sort the ENTIRE data set not just the displayed page.  Now, I think that means when you do that, it pops you back to page one...  unless (and this is just a thought not an instruction) if a star is selected, that star is at the top of the displayed page after the sort.  That may be too much of a pain tho. 

But I know this, if you click on a column header to sort, and the system just sorts that page, that's a bug.

**Comment by ljramones** [comment]
ok, I have 100 stars a page but I can change that to 50.

So what I understand it that you want to be able to sort base on each of the fields and then after it is selected, we show page one.
Correct?

**Comment by BoatrightTBC** [comment]
That's correct

**Comment by ljramones** [comment]
ok, this seems to be working now

**Comment by ljramones** [comment]
checked in
