### ISSUE TITLE
Query function does not return good data when querying star class

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#54]
If you query the 150 LY chview data set, and run the slider to the right to include the ENTIRE data set, and then select stellar clas "G" you get TWO stars!!!  

Why?  Because the query is looking for exactly 'g' and ignores classes like G4V etc...  

The stellar class query needs to search for ONLY THE FIRST CHARACTER of the star class   

A future enhancement would call for a checkbox for "Other" and a field to enter a value so you could search for "G3" or "M5" -- but even that should be a substring match so that G3 would match G3 G3II G3V etc.

**Comment by ljramones** [comment]
ok, I'll look into this

**Comment by ljramones** [comment]
searching on ortho class now works. 
I did not address the idea of a general multi character
