### ISSUE TITLE
Future Feature Request:  Advanced query.

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#57]
We've discussed many times that we want the query system to be self-explanitory. 
**However**, many geekish users will want to be able to do more complex queries than are possible with the query screen as it is currently designed.  

For example, What if I want to see stars that have polity "Klingon" **OR** "Romulan" **AND** have space-born military assets?  That requires the ability to do a more advanced query. Given the names of the data fields, the system should be able to accept a request like: 

`SELECT stars WHERE temperature > 6000 AND radius < 1.5 AND (polity = 'Klingon' OR polity = 'Romulen')`

I know not everyone will be able to use it freely, but the geekish ones will want it despiritely.  I'm not even requesting it for version 1.0, but it ought to be in our future ideas list.

**Comment by ljramones** [comment]
I did some research over the weekend and this is simpler than I thought.
I found a SQL validation utility that I can integrate to ensure that a single line SQL statement is properly formatted.
I can add an aide memoire facility for users to see the data dictionary of the database attributes they could query on.
I could provide a mechanism to allow users to see if the query returned data and then chose to plot of view it in tabular form.
BUT,...  all I would do is validate the query and return either results or tell the user why they query is invalid. Only SELECT, no other command.

Probably no more than a few days effort.

**Comment by ljramones** [comment]
Ok, I added this feature.
You select the dataset and enter the where part as a boolean expression. Part of the request is to is to select whether you want to plot or view the data in a table.

There are validation checks for legal SQL, checks if you don't select certain required elements and where it warns you if you are selecting all the data

![image](https://user-images.githubusercontent.com/226595/100029848-2b65e180-2dc0-11eb-9c4e-d4cd2c57e913.png)
