### ISSUE TITLE
Text on Plot Stars dialog is wrong

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#58]
If you select **Data Management / Plot Stars** you are told to select the data set you want to display.  That's ok. 

**BUT** the text in the dialog box then says that the default display is 15 light years from earth.  
    No, it's 20.  

**AND** it says to use the "Show stars filter to change" but No, you have to use SEARCH to display some other radius. There is no "Show stars filter" 

Text should read: 

**Select the data set to plot. Default radius is 20 LY. For other distances use Search.**

**Comment by ljramones** [comment]
This is already been changed in v0.5.3
