### ISSUE TITLE
Failed to load Colonize.chv

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#68]
number format exception while loading this files
[terranrepublicviewer.log](https://github.com/ljramones/trips/files/5213292/terranrepublicviewer.log)
[ErrorLoadingCOLONIZE.CHV.txt](https://github.com/ljramones/trips/files/5213293/ErrorLoadingCOLONIZE.CHV.txt)

**Comment by ljramones** [comment]
file was corrupted so unable to parse
put in more error handling to show why

**Comment by cegannon1** [comment]
I am going to try my version of the filed, see if it works in CHViewer. If it does, that means one of two things: 

1) the file was simply a corrupted example and my version could be used (which is important for me in terms of invested development in terms of bakcground)
2) there might be something else going on.

**Comment by ljramones** [comment]
Ok

**Comment by cegannon1** [comment]
Well, this is still weirder. I have gone through all my old .chv files on all my old machines and in all my old archives. Nada. Am sending a few that may or may not already be among those you have, if you could please check?
