### ISSUE TITLE
Change Star view preferences so that color and radius can be overridden for 

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#71]
use the following preferences to change color and radius for all stars.
color is induced from spectra and radius over rides the value form the DB

![image](https://user-images.githubusercontent.com/226595/93025453-143e9280-f5cc-11ea-8e80-17ed851a0837.png)

**Comment by cegannon1** [comment]
A Lot of these colors will not show up. Sorry, thought I'd left a note.

O  = lt blue, siz 8
B  = Lt blue, siz 6
F  = Needs a more yellow shade
L, T = same color as Y

This ensures visibilith.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ljramones** [comment]
ok, this is now in the system.
Although I read radius from the data file, the above dialog is used to display the data.
If you change the data and then replot then it correctly uses these sizes
