### ISSUE TITLE
Add miscellanious fields for future use to data set. 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#72]
Add miscText 1 through 5 as string and miscNum 1 through 5 as double to the data model.  At this time, just leave them blank, but enable edit in a future version. 

These can be used by users to keep whatever weird data they want...  What model Cylon lives on that  system, how many cities over 1 million population, Primary ethnic background, Primary religion, whatever. 

For now, these fields are not queryable. In some future version they'll be enabled in an advanced query capability but for now, they're just unspecified string and number fields.  If we need to specify a string length, let's make it 20.  I don't want them to be "blobs" like the notes field.  Just plain old strings and plain old numbers.

**Comment by ljramones** [comment]
done, load, save, and edit.
no querires so far
