### ISSUE TITLE
Make trips resizable

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#73]
At the moment it is fixed in size.

The goal of this is to make it resizable to allow for more screen real estate.
The difficulty is that a lot of calculations are involved in keeping all the parts happy.

**Comment by cegannon1** [comment]
Understood, but there needs to be full screen version, too.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ljramones** [comment]
yes

**Comment by ljramones** [comment]
I made it resizable, but we need to discuss whether to scale in proportion of take advantage of the new sccale.
