### ISSUE TITLE
Problem importing CHVIEW data

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#76]
**Describe the bug**

When importing CHVIEW data, some of the datasets contain star names with a double quote (") in them. 

The import dataset process for CHVIEW datasets sees that quote as an end-of-field marker when it's really just embedded in the name.  As a result, on those stars all the other fields get shifted to the right by one column. For example: 

`false,0.0,0.0,,,test1,0.0,0.0,BD+54  1861B",1862,68.15,false,,0.0,,0.0,0.0,0.0,0.0,0.0,,,,initial load of object,UNDEFINED,false,0.0,,0.0,0.0,,,,,0.0,0.0,0.83,0,true,0.0,,UNDEFINED,,K8V,,,0.0,,-8.53,-38.65,55.47`

Note how the quote after BD+54  1861" pushes 1862 into the distance column which should have been 68.15. 

As it turns out, this is the same error that resulted in some datasets appearing to have stars with the radius set to 25. They weren't, they were just column offset. 

Since these names are embedded in basically all the CHVIEW datasets we have, you're going to have to parse those quotes out of the system before bringing stuff into the sql database. I would reccomend replacing them with space. 

**To Reproduce**

1. Import FAREXILE.CHV into TRIPS. 
2. Export that data set to a CSV. 
3. Open the CSV in Excel and sort on Polity descending  or  Search for quotemark (") in the starname. 

You'll find a bunch of stars at the top which have had a column offset to the right by 1 after the star name. 

**TRIPS version** 
- [ ] 0.52 
- [X] 0.53  but I expect it's the same in 54.  
- [ ] 0.54
- [ ] 0.55
 
**Desktop (please complete the following information):** 
<!- Move the X to the right line -> 
- [ ] IOS 
- [X] Windows 10 
- [ ] Windows Vista, 7 or 8
- [ ] Windows XP 
- [ ] Linux (add distribution and version to this line)

**Comment by BoatrightTBC** [comment]
When this happens in 053, the program complains that the data to import is corrupt rather than importing the good records.  I don't think that's right.

**Comment by ljramones** [comment]
ok, I searched through the raw hexfile of CHV and that string >>BD+54 1861B"<< doesn't appear.
You say you exported vis the csv export function?
I've tested the csv export so I believe that it probably have bugs in it.

I'll fix the csv export

![image](https://user-images.githubusercontent.com/226595/93689992-bfa28800-faa1-11ea-9c79-5563ab7b8870.png)

**Comment by ljramones** [comment]
this is fixed. The csv exporter had a bug
