### ISSUE TITLE
Query is not returning expected results -- or I don't understand what it's supposed to do. 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#78]
**Describe the bug**

* I edited three stars.  In the "fictional" tab I set the polity to 1, 2, and "Human". 
* I went to the query form, and checked the Polity box and the Human box.  85 stars were returned, all but the three I edited had "NA" in the Polity field.  
* This seems wrong. 

**TRIPS version** 
- [ ] 0.52 
- [X] 0.53
- [ ] 0.54
- [ ] 0.55
 
**Desktop (please complete the following information):** 
<!- Move the X to the right line -> 
- [ ] IOS 
- [X] Windows 10 
- [ ] Windows Vista, 7 or 8
- [ ] Windows XP 
- [ ] Linux (add distribution and version to this line) 

**Additional info **

**Comment by ljramones** [comment]
looking at this now. The query is broken. I'll try fix tonight

**Comment by ljramones** [comment]
fixed
