### ISSUE TITLE
Generate Distances for this Star and Save

### ISSUE THREAD

**Issue by TinManOfGames** [ljramones/trips#86]
**Describe the bug**

The Generate Distances for this Star has the options to Cancel or Save.
The Cancel feature launches the Save Window.

**To Reproduce**

Steps to reproduce the behavior such as:
1. Go to Reports
2. Click on Distance
3. Click on Generate
4. Click on Cancel

**Expected behavior vs Actual**

This should go back Main page or selecting a Star for the distance.

**Screenshots**

If applicable, add screenshots to help explain your problem. If none, delete this section. You will have to have saved screenshots to your local drive, then just drag and drop them to here in the editor. 

**TRIPS version** 
- [ ] 0.52 
- [X] 0.53
- [ ] 0.54
- [ ] 0.55
 
**Desktop (please complete the following information):** 
- [ ] IOS 
- [X] Windows 10 
- [ ] Windows Vista, 7 or 8
- [ ] Windows XP 
- [ ] Linux (add distribution and version to this line) 

**Additional info **

**Comment by ljramones** [comment]
fixed
