### ISSUE TITLE
Resetting the Star Field View

### ISSUE THREAD

**Issue by TinManOfGames** [ljramones/trips#87]
**Is your feature request related to a problem? Please describe.**
Moving the star field around, I have ended upside down and way over to one side.

**Describe the solution you'd like**
A button or buttons to allow me flip the Star Field upright or upside down, a button to change the view to edge on to the Star Field.

**Describe alternatives you've considered**
Mouse manipulation. Centering on a Star.

**Comment by ljramones** [comment]
put in a menu item and toggle but to reset the view to the initial
