### ISSUE TITLE
Full screen option not available in main view screen

### ISSUE THREAD

**Issue by HiverLord** [ljramones/trips#96]
**Describe the bug**
Not sure if this is actually a bug, or a functionality request...
On a Windows10 laptop, in the main view after opening the program, or any time in the program, the normal Windows function to expand the program to full screen is dimmed/not available. Having this while viewing the map would be ideal.

**To Reproduce**

Steps to reproduce the behavior such as:

**Expected behavior vs Actual**

A clear and concise description of what you expected to happen and what you got instead.

**Screenshots**

If applicable, add screenshots to help explain your problem. If none, delete this section. You will have to have saved screenshots to your local drive, then just drag and drop them to here in the editor. 

**TRIPS version** 
- [ ] 0.52 
- [X] 0.53
- [ ] 0.54
- [ ] 0.55
 
**Desktop (please complete the following information):** 
 
- [ ] IOS 
- [X] Windows 10 
- [ ] Windows Vista, 7 or 8
- [ ] Windows XP 
- [ ] Linux (add distribution and version to this line) 

**Additional info **

**Comment by ljramones** [comment]
This is already addressed by this issue:  https://github.com/ljramones/trips/issues/73

**Comment by HiverLord** [comment]
I saw that one, but didn't look too closely and see it was related. Thanks.

**Comment by ljramones** [comment]
np, thanks for thinking of it

**Comment by ljramones** [comment]
closed, resized
